global:
  clusterName: hcloud-vpn107
  kubernetes:
    version: v1.35.4
  kubeaid:
    repo: https://github.com/Obmondo/KubeAid.git
  kubeaidConfig:
    repo: git@github.com:sbdtu5498/kubeaid-config
  additionalUsers: 
    []
provider:
  hetzner: true

hetzner:
  mode: hcloud
  multipleSubnets: false

  sshKeyPair:
    name: private
  hcloud:
    zone: eu-central
    imageName: ubuntu-24.04
    cidrBlock: 10.0.0.0/16
    subnetCidrBlock: 10.0.0.0/24

  controlPlane:
    regions: 
      - nbg1

    

    
    hcloud: 
      machineType: cpx32
      replicas: 1
      loadBalancer:
        enabled: true
        region: nbg1
        endpoint: ""

  nodeGroups: 
    hcloud: []
    bareMetal: []
