---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBItoR8UlBA7ak2iW41NDi/s6gnIxW6+1fQeXIY7khqJuGmpyxd2Idd0aBMJo9/j05+zWLD/scmyDrC5MvTd9BrEp1nixvptA3jD+S49iDNIeuryKVAuXg6Q2Ow144hQqiiwmJHAmxD6U1hzbbmAjnLv9YJlUQHm3O1o43+cCCsnsCNqzlsLMLBCBdNUN4d4IDyJNDb3lLYkzOcRdeRnLOiNovpZdNISGSTxhsPbVh+Dpei4xwxzDk1rdp3qHXchpXUYoRUmFoXEOAd5M7LgBQNP+U0ColVc5BlyEDbl5VPF8whRXS8mo5OV5ztcQyNVUxamHj3+RfNODtNU8zOaCd+cSw2iCeppfDUZCDCQKEwMV45+l5iJebg/bnMrSADl9mF5g84hFZa+3Uu9vQmv8QO4ows4pq8PSd45fsXrATlV2w6pqbRxYHsswCW08B+a739zt4AVwO3kM0xGiKsgsnloSRHmiLEt5KluOssmuwIy+Nuwvy5OyYDCu53pk+FSog5IhWmUrVXnPz1fRjsKCMf6KeliQ0B7WyK44AJR59Xl1tWzg5eyiZZdli8YgBeGM/XI/wq5rUA2sI2Nh1FBFxfi3gA+ee+wITxED9oj9IZFhZXf9701hYkzU29xbe6ClZcCVADzvThR2V95i3+Utcz690WAZftjDOJWBRJNqJaNzQr555q6B9ze6w1GIxMXBjrbrgqGEcICDu2B5VSwmuZCRKftX8+73ZfMzscqfJaYhgLAqhxE8q1J4ZyOfAyK2KmjnrXoe5X+jn1yyqt0fNk
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
