---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAoaxLtpVQ2ngZkoMrJYLt6qhY1tEpB1ZK7Ig1O8bs/A2LI98p+FY04lnPpdfH5bNnMaNeiAC0PhHZX0MfVy6CHfiIezX6dPkc9J1QWe/qyhXjSmAjyTFIfTXddBWkOhtb196X5tyJ6NmIwCnbMONuIlgI6LlJU5EzaHxwT7JytsOtT4Y7FoLgZdD+rKvxXsgmV6MkfHK0EPLEyPwzFn0I8sowCEO62BJGNVBDuqm8ChxrN9eCW4fHlCIwzoBVyFpkhuf5lAs4y9Q90fyKVB90pSUVMwP/F+/ZPOovYHbYnLOA28hvuknzWJc38vHs1ao3FUcc024/cTeVtfgWqQTSbcaUQDt2vsyCHH16PcOZNQcS2IMsa+jQJ/U4+ahMHKiKr+Xoqr00leiUEPmIFTYEnkKV6SnGg7WXjlRHuO8tWhD+X23Lya6Lh5BEfQGnnI7uTCeXn/dBGxOImR7OFfaVDkgOG8yrArRe6URNItUO6ZL9xq55ZJ2lc4J8gHbrCjD5RL1Y99e8Xw4NR+aETrGiNjHW8Vqn5H2bXFKI7s1AMnfV7eBb61nWUnRrYP1AjcC+mJedWQNX78KxK+a/Sq8sNRkIXDukXFfY6nhdBE9sMGebtpF6ur0pgzO+3fGb62aZ+1Yh2MljTOzdn+erTWqV49dCNp2rKowZIFh86yj6QX9jVTNqejIX7oO0aXq0yT9Ogm0Ed5vsFEmMWcBcjmSyXTfxo/GLKCd0BDauFCqmBN/dsuPeA0LW/G2f67KDL00b0bNeqI5yDduwbqIgaqSS1
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
