apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAloaRADcrsblmgP/mtLzOWKJabkyRPwnZz2yhduTSknyec0GLqJ16MWNrtLP+EI+3jgrEJKVtmDmn3MY56uBfBq0WA7W9eDDRjCkfNLZikL0X/T9Sa6wMJo6AUKjNMAHpb45vqaxB8jt64bMSYKQSN120iqqB82+QD1mdvqDlghTW0uT9l80I/FI8wtY0hzUyB2qBC2/LK0ySxkYbvznkC7D5WzeLVHg2lamxVFSS7AZFuPSBDoSo5Axzgjs01HphdAWF5+FUx1fSPvQJ1Zz3U7aTk1AlDB3T6HYNk9MPyxDn5tk1JzCVuGBKdQDhX7Xdr1X5UNkdhkhqr+CUaYLIz2YCA/FXcTue1Q+oJD0hApeb3y+Q9EeBuPk1KC/tVYM4FlPrMQYC7JtduJZaXoEvi2OEZhiNjD+j4rnuhyajtRTrmkdMC/SSEGcIElEy8d5uf/ZW7IDgftVR0wb7JEuWTikv25AR7Iqs+4IKMAjnrpjSiYRCp1kWSLdue+NDciaDyT2whtjEVWiyUelQAOSs0NypvyH1ZndTByI8sE01zfJjLsNdUR3Lo4GTbB7IXJe6J3gs9bLoDcanW/y0Q8Yz+4LSib7iPx7XtYmBoqNCdYxAbBofG5IXZwcNMYoUHOinPq4I7a0QODTkyHLuw0gj9iQwTXSgcs8GN5L4FP9y8oVJn0C0vGq2aUG0uRR90Rez04DM9ZYKMRYcwD+o1WQHWUucmKiizZXSxZBL5TArAHHzsp7l/aNfnE8Zj5kEP2UGviecG1ZHnf2xNvFhKXuYb
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

