apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgB+6lutI8/j4Ap/6PhmDSGecvZ96Ld2X1oKVgNWqg4TfMr60LSAoHxENGn9wslR0Z8u3hmLDvSc2V+CSArlkuDCLxREP92hYLjSQWJxAMcVH69Zl71WOzChz+BaTZmClZ1f77P1X4IYdGJVyz5yEfNah02eTz2ppUKlL5POalqpOsMrnPDrXOhI98pWNnPyberSffmtwjBJd9HA0JeUagKsaA3Puqj7EXsjfKhaWtnikTPrES6zFA1bbtd8JCelCfN0XvqM+uXw2vM2qeBReWNyNquicrramt2jju1YTjN3/SWg4k1t8TQyrp2ULY+k3Cqz7gBYNQnbXydxkRJ/xGo6Gg52cPmavjhedfzPB6oWrPZp3Q9xKX8jRsdtMN79c8t46pcP4KeKZeJtr/Xc+bgQ1TmUR8vdxxTNhtRusu4bnYpCgzQ32/2Ht87CxbHX82mGN7LNm8xQwnycE+YiXruv8BrtrFsCiwvMIMsBKOmoR2UCc7STWulvBY8Nhr75RozWwqJBxtEjzH4DpHHJ0ReqDbb5ytQxvzUshhLv5C0sMHJxuNlPvTCbBBiFVHddwQPkihZ3wkkmF8+gN49BLcYKzrfyMtLQoKaN255PqyPcHUNtUXoplBqYbk5kak+irpQyI6cuQ5zXblY+VZzcjBmx8UGJzLn1BPvB0X+gqrRdeDf4+ciAOcvN5nJ7tYDD+RI/HEBzuX3B4ox8g0uLJDASqbzhroHE5qWQ2mlaUpepJurHpufHfDU5GStx3n2S6WnuVu8pXlEbZgbO0rUcZt8D
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

