apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCLmz84iCKsRJgRPNm+N2fZmNIzLrZw1eTtXl2w5F1cfueieKIQ36//bMpnmf216wPScs6Pqm3jUVfy2n9vH1Jf1Mlu9m7WGPcw5F8clEnyQu0MSTBMocPpEdWDP0MkDGA/6WYyGWpMz+FqJvnJ12ju9cz7akyc+HDpne732knSMBxqmPTSGt6VipIAC+MeVLmk7tvJllxXlh80imXFFbuEJIc9hyD38wC9O5CzGjcJ+oTmEEUKFQ+6uMKVDJ/f2fHQRF6J8/d+ylV3G5TtlIz7G9zXuJF0rZYmYmI+Isix6pLvXB1VdhP3mY4Kpptylzm7QPaMlcKys0Nlsw8LTeavS09LxOpWL1h+ELivVt9tgx91TRTc/s3I6f/tfbquzKUpxJIyHVKwufjCE6EPf/uQ3isT3JU7l47j/1MkM+9rbS/j/oCiJSyIz326ruyq486LhvpT3kIXCeVPvbVu61oUw5HmzjoMfbYVGoaPGwUpXz4FVOynA3HjIZeSfie+tsC+LxwCmesHx03juruEyUFKhucO9+V95KJ8hnsW/OOX+t76rmk1CCddEgKKlaqAqfn12nnbzVfGiuV2+jIflPBBefiswsOwtVjwWZnfSruEBK59IwC4h99903E+1GIaNnhRu2r8sR9mhIX0BGjghdUNWkwomg/jMJ3+7TRFFWoz/N3Q0OxrJrDyI5WolRRBfcqiMkW4EHxG/mf99gvbsGT9J4pysOo1izqRRXN5isoji7IIm/vr+xpt8gnr4jPWU2MLW+9Vx9V82qXENK21s6kO
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

