apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgClqebAGA8sqC3dOwknhzzSJ0xwzuKVr6nyCR+nmEI47WP33krkc7S91CWS0Lny4PUGuoePj9zIEBhN7IUhPsvoJ6dMSTzGzWYjvf5iGrhvTaVffB/jSt+Qr3mY9iDzFfrF15jmVuQL8aK68T3kG5ziqz97kCxh62AyncCtb4EvsNXt/l57K8GepmpnDtKbUGh+wlEuVnbxfjIlt/28Vj2o+zDv9FjlMFglOHjZVjALsyz1XfuiB/k5hry2yMxNFuMxqhngLLuD5xYqh74okBX722W6qNSKtlsgG4qLXVsga57xRsAdbMxzRmHFFrwRH6uUJQUoKzCGjzGWD6IVc/oVk8npP+j51PA8HJZENFPfAMEHcbQtLu+ZTYsPE46uvjDnmALZ5Dkx0+BYrIYwTm5/afd0jyF0GMkW+qBXplBj+Y5iUi/KIUlzSpJSPvHIYidv9aFAsMT5ZLrBSy6erD+If+W2bcbfykaLBHYAj4OhBnSDzT1WWk2j82/v91ulDGSMVtboZpQD1Y2P7G5tsU1S2BwJC7Oi8HJSK7ME4i9YDpI/ELqueZCVfWJpdpQbAlWAC2pordm8dRmbAQuk0g/xPsebceOKxKex2fqEKnG4NFI1+xFbrSYL2sMzcxFDoxVCQyuZ8x+kzh9SUoahUIFNzHbu+RScVlSQ3o53yt6fGXve9/zj7Re0P6muht98pXRCTOpCzZ7yAnsOjkbd2eSqyl1mZDioVhZIDCiLR+K9UC1d5FBS7bpEBWJkxY5EUvHEEa0yrAdB1J0njsewPhnw
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

