apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBOSRN+BuKrSHl/y2a4RJxHrxHAXZs8ZAlcX8ot23O3zG2WN5X05VKO0+w18O5KRivpTjWfo1k7+nUHKqO1giT1f1qdCZmBzEXQ8o2OUZd59RaLqkiBEKNh3UzlX6ulTlObKLUADiy7zYs6ReprEIK100I95282wfnQrY+8ulwcU6Bl3m04dV9Iv+AYtDslkzT4P9jqCT5Di9a6uxgh6Wst1Mc2jOgvvhXDjf65PkhCNW8OMJciCzpbgxVdLjzME3g4PyrgeXH9zBJSw6SNxWl5v+676CQBCjtEZchPfO3sHSGEk/w0WpszhFA1dv1L6phJ1almxB73q2tYpJjQWtw1XiU0uhaFoFbC4nP4XiFeBfRo5qnvjl7D14o0RSqtEcPJokOr1MjH30/oA1H0QODw6Fedwb7s7pGvgyUt8hAxd4fmyfy1hlAMhw7uG/rSAPHpdloHetlusz3S7A191eV+q6TSTi9zYzaHdO/VOi0ETVfk/WY7ByHrF5OghKbHRuprR2DI1+daa0QFuipfDk/VG9mhOBj1eYp3wJWEV2y40TcorN4U3gpWwbcMrmWPyXvuGzrBaZRsqOnW6+MR0SJB+UuEDNAPqfB8NeQtjynNWPWdUpEoZZae/eJvYvxm5mQ0w6C8jsb4pfaIMTJ5AZ6O54YGKJr/F1lvfDqt1Aa4cbdFqP57sGiMmzz6an05k8xLBFe88ejAMO7pEczoP965xgj5v6Ds/fx0ntvr82f+xaTNdSCtZ22q09yXsodPI5S9LsSdD9HNw+7gCUActiOc
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

