apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgClqwcIioADBzvHYM4Bu5Uz+ErIClqqe/uC7/0DATBpb/QmRQPDiEgnTQ2FgWMiouTssNUmxaffDN5M2Z08728JLC5sG8DgZdu0yOuUB+i6a0HALBfzd/EGCKcGOvfYA0ltWvq950++obDgP8cb3/IeB2v9CbF5voNQWIH2k28e2W91rbdU5KqB27XyQD7qtZ4n4CdXFXVLLX0e+qWdj/Zrb8bBUH0kqkXG03oIBRfWZjbJyXXFr7pyzaw6SRyXIcCqCfy44hm7H0bW4HRyZXev70k1oF9FAJctxydj6P64d35hR/Fq6x3wBxsbQkZFAMcHosMWjylswPe2xpEiV1qa7/vPizlmLu6VFyZkzX9vBC/EF1zupdGEZe/gQE1+KSivTKqW8wZXv/kGmD1XhPJCHpGtVG4M1VhJU8I4fVDN5u7eOoljG2zxaEocKD2VzWJBvBxY2fXPtnNZGLNXTwg1+7YKfUsfdZ0d+lUHfOeSSxus+SQnl1ziGjtGEX+KrFHcw+TmQXnzL8xUZk9Rmm0XIloYfEhv6Cqdn0+4gJXEXhCDW3y5u5Hd8pCHsqjJb+NxZy69PtS4g9CoH3aknc+wqtqIP+6ynIF4Il5VbyM6XmI+UMu2Ccg8RczPnqsly2QVYCd1otiiYjKvSancnXdufBliA1Qx47UsX4OxsrmMHkqVIZ0sJatJ8Jh4ril9eQurnC++2xE82KS2+nFAw0R3mr8xmo1bzOPzpULWkzN4M+B4BnVK5nPxp1zKdY1b9kHNIBGkLEVL7zaVK3+ZqrrA
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

