apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgDRmxu/20Ml7vuk5WgZHi+lpQlYj5XKce7Pe4ICcl3RuQTI1QZfVUI3kgpFa6X37SURq/FlvSlmLrbtvNWKXnOwUWXfsF+qDXNtMSZEAHC5MVMoNGEM7UqtmWW+XsVkqLOpoXzJkbfHtxqLBdk2PEgSXUdDOaJ2bu7liRlA53oOyEmTIdxAIFVgEgudZqL76ZUn+s4h0Gmjf7LTI+RscCOwTUiitGPVTFf9t76a52oeRfFLRFKzZmQqre3+Ert9IJ9WMnQwhQHIAqB87nUwpAWNn7H/eoHUrEcx2jPaR+/fGYmCCANALigaQiHuYPj3lLq3N5PY/Mwk0FSIeS0i21jRhGelGN0c1iw+ZsnVnJlWBNzCT0uf2gY5uqzsU6Jo4LngvGnrqBzez+MepJvV1AVqJ3uewW4coB6UDZSwGcVmFTOJQntVYOQGlSUZTzM8YSh44o8DJ98weoy4m59qKTJ/pKlrlikBu5kyGLjr8nlKCy0t3RRET4E+wIaf+kb8inO4sWab7WKegOe0Z73lyPXIkWIpUMdIg3y5SmkbtBUmluw/9zP1/eHqpLlESpodXOWG4MEfSJD49ALyrNShPW2jc+H21/RqI9KtQPqypIZKC5Xil08tI2ejsnFtdIUF3tjqgncg+q2bF034UWKtlyJKoSIYB3Zm9ZS7uYIz5+A66B9c9/mNInPWRCXqGdbzddgduguqyosyXMd2Hz1hoW2mrBj/xWj0718WdmgSmmRuHatK9F5R40a+p3EA5O8GwIvN9T6jPHYK8OKhAimvx6jI
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

