apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAEcvhH7GKqn6sWO9Sb41cbuLglbbbxRVxeOk6N5sVcoWlpzY+rYuoZDZc90bRPqRPuq4KDD3zNgWTEUaJXEM651DTuXsJ9zDlYHPXEpnwFVXDw6aAc3JKGN5wvalXd5A7ooxH9Chyark+BXj0y4ccwSjr64AFdIvsX6Qex6/WRMT272NEnMJChUJUI+yhD445W0Jcc3a+tfWzSuv32WSTm3DmXZ4HM7txWiwG77wVNtlYxEBKinMpexnJhta2hFQo3Dx4r1AZi8/6zNa8dqstrPmoVKzeHy5ddooWP3FNnphDID+aczeyMn173bt9j5ClBj1WM2F5ZChy2S8WmgkGLpY7qJGN2MoS4EsgZAWzvZqV6pqjMqWUx2FrV2n3wNmj2O49q0z0gx6NlvB4/N2wyTko0dFpakt26KDecuiB/lBr1pZrrV1P1fvYN5G4SNP0h5i4NKdM0GjiJqlYktUIGJ9BZlibNCiz1GMSjlMpEmwR3/rg4gs5NhO2QeNPT4QdW6mkU72AOAY2dNkyWrmfWKVXlnea1i9l4p8EMLyEHOXo/qAvd2j/HJg5VFXqhTuJYV7GTop9aOjetb4TcVmYOXtmzkVxk+OFs0H1xcYFMk+lQv+yL8QsDG57Wz/pyuVZ1lC2qjASpiBczlHSA4ZxF/r8IFqOlMIhp+1jHVkFoI8EJf5NW9zL81nKg3VDhCsHB9tTHtKd2YKB5fmYEDOs0Lemb+8v47r1sf750ezpuYNZLp8mwNAtGyqJVIFZKkVj3NVexCd1NyX8MCNAESdc3
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

