apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgC7423oDntu1cS4nFWbPRbrywOuXl2EnTuqb8O2bYhavpog1GkLzL388MCQ5PhUQUIzeO2zCLPNRXvENHE6DVU+oilPICpQD4Fp0RAEve28TUPmyjZrK5BSy1I2afbGLe48cxm3q8cvMWIKSE69V2JtGVhx54BcUqHxQDh+HhAbKEs8BW1uwZYTViNQq841S+3uOSx3RXPn6QNb+hUnk6oxbYb2WZNyMvzKb07gcYu2//19filJziY1KyguQ8pGnfCdyR31M9b/91cobUlUyfLpkZeFhp60Nf4+qZySkOjBHqiEXQ4iqGCkxm0M71fRXd3Jawqigr7eRoEDcw2TzCmy8VgX8+bwmZxZ3/7x/MnaNz5H+lXlBhpZRq2Wul396X7KecrFkyEGJ2NMB99P2S6bgW7uuQxxiAC8aMp+ZgO3YnErKVm1pVrtX225uXnzJEAseuc5aD4uch7S4pspxGjkuxaKPK9Lq3nuEz9CcICtQcUd5XJI+TDryy6FiEU9rImfrW92I217+tqP9PwILd3FwFRr8zLDOk7dd65qkauUw4JD2nT56Mkxq7dv/GPaJ5yjQQFR6eWIbRL3hyROkVIAjKW/0hwkU42wR2vzUJM0tAX+gvBpMpFu/7QOCnMhIeD+8l5hNDtBLJsvLaCDVigaHssYyx3h4XJQXhUTh1BTWnssYbs0X8AqyVPS8OiGQtdiOWeZXomsu7e9O+s9wt3riTlyMY36kkToNPs0a4i5kfH0fN9D95asMA0m9BVGk8IDKhO8jyLSwRlnUDy+FUI+
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

