apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "HEAD"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: capi-cluster
  namespace: argocd
spec:
  destination:
    namespace: capi-cluster
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/Obmondo/kubeaid
      path: argocd-helm-charts/capi-cluster
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kubeaid-demo-hetzner-hcloud/argocd-apps/values-capi-cluster.yaml
    - repoURL: https://github.com/sbdtu5498/kubeaid-config
      targetRevision: HEAD
      ref: values
  project: kubeaid
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: cluster.x-k8s.io
      kind: MachineDeployment
      jsonPointers:
        - /spec/replicas
    
    - group: infrastructure.cluster.x-k8s.io
      kind: HetznerCluster
      jsonPointers:
        - /spec/controlPlaneEndpoint/host
