apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "HEAD"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: https://github.com/sbdtu5498/kubeaid
      path: argocd-helm-charts/cert-manager
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kubeaid-demo-hetzner-hcloud/argocd-apps/values-cert-manager.yaml
    - repoURL: https://github.com/sbdtu5498/kubeaid-config
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
