apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "HEAD"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: cluster-api
  namespace: argocd
spec:
  destination:
    namespace: cluster-api
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/Obmondo/kubeaid
      path: argocd-helm-charts/cluster-api
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kubeaid-demo-hetzner-hcloud/argocd-apps/values-cluster-api.yaml
    - repoURL: https://github.com/sbdtu5498/kubeaid-config
      targetRevision: HEAD
      ref: values
  project: kubeaid
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
