---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgA+1xPlFfxKHfEg0cgabEDTl8BCG8D4lckcdV3/4CK/VXpFGGgIT8kQ8PoMLpzp/XeveUg5lw9NI9Ow1dKwHBN0T6gtGrToMLqLcnKXfoc11W/iJdJ9uYgZ7u3QdTuMtUNd7UcSb1QhuPVk6rqV+146P4XFNskMogLB1nNlVA0M7+SoWGj4a8os2uj68R3HbpSwqEcYMvOBFf5Do4UqdTM4TvQS+VJ46XTVGffk0IVIOwhAvy0nzfvKx+YW4hndR7jDaVb7pAnwujT1nuIDOMD6LnrWCHoLYzjRsQiUgvkfROh3l7uksaFAD3oL+NV2M50m2bKEB0oHobzLedvKCQ1h/46jJ+4rzbN015Kl+xEQYXgimkc17x1PpJQ4NsNXWJNDw2Ny+8PDMzXsLbJSdRJc/w+DDKhHU3qW1JUqm1lG5bInFg3R7Agcj3f/sSVLbf2OEdSgokKMKqivxCnjdL8i14yHIOJlTaEltqCFOjU2OmaK7aJEgZAnqcvM/SqrJ7D2iP5JMJwZyxBhWFOo89Yv4OibMZs3qTZrfRve42pSnVSHWzQLvk58Pe+oDqXSQu6Zt4r8WcNAA38KnckFuV+ynKXQg6SiI/3KfVl5Lstl3OnUUnYSs7bcxX76OiUpexWcrKvi9P4HT36G2D6EN/bbaUCSlAsx80RFHEwds3BdZYt7Y+xQ0QuO/uX7yQ09eGFMxN3bkdm74buZLSmZSRdc88bxy58GdncR9zvKH6U3s0O31lfTgEk093k/x5yrHajOuAD7wPBGstfAtNniEu0z
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
