---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgC21M/95gNFjkKfvhRZODBa2GiDxQmNoUnRMrb+xFrV0bHCdXZB5RhxdpX7673E5g7GTmi5Skjes0AzMWrmzm2CPVNmkMj0jP9zvkMhJ5lOdOB0WmbLbzSJ/ByXRKb0QPKxTrTQhVL8MmtXza59ORafZt874V3i/gTfdnEwcVFgv9qWNMtZRzqBMvliopCY1nCIee0IWmdO3lGlCdv1/fFc+c8bqifVZdQWHgmT6+TzOEJm+1F3lwTxhYJGQUfu604TuqJ3SqpKscdyKRLQAACz/co97u6yukAdGig74shMD24inxWRRd4ymrJPaLNqYbNimYrmzP1P7VlWmTAOiYI1h2EJXdygrW7pobdUcjx92QSe+WySu+NoS/6+XtWNAd5E7n0ZyAowqVsdwJG9mgzoWb86P1eTfGsUP9yvYWgp8cDJkp36oYScZRaNXIh0ePm4Tzfep9/y2YY04UuWqzolKLv12UiHYxFlmU7bYAgbA+c/h8+Jcl1wXiYYy4i855lmXThEMLU1brkbJxLoaAj/UbmtJ4B5ImHCca8wGGyeKtm8xLMVMYNy149W2GBIrOraE9gKFbWIyuv8K+ZNsMoGldqlnDiAUSxgNo+8HhdU2GczCKBUwEWQbBqbBVO+fu8wsAt3FL2FJR7XlLsFnq3hG1EWj/CSQpRZsflrllaOOENooSbLAhWLuFHPKnJL9LDAs1HJxWcwiUhRtAtme6jYJGpS6S5tnJoWFwyDAyfAH6Cuk8gTYl2HMIPKJlNKbX3W0Z5NL354Kcl6OPhQ0q4g
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
