---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBaILgg2vbp4eYxySxnEB5pFumwiz5JhdLzX6TDa7vVn0xmFJbOkoBgUoQiQScr6+sv5T0Vl91JBaZNPK1W+ATLuZ/zt01b381vm7Wrvr25+wptgrIQxHThP+YOzKb5+4jcw2LCeXgYfhYezefbK6o5PzoVRS5EkdL1tbkIBA9xQx4rRUZ2jpAWFlrv++mHWsmznaG18u+ctaiK5bALqbbOEpgmSsIOWVFbi/3R0yNIP/gOWFJYyUxYckL5XGf1/XybxJcfVQVm7r8ndA48xabBfbJny+nUu407poRBWzW8A5Ebfadn+t2oZjZMkPJzpRX+oZSg6tbSu5prMok1eVezm89Y60KBkGHQTPeIeD5EYp1Azv5jZ/VcjbWecjnhz2rm4ZpjwLqZ4Co+HqzlsQunW3dsgbbgB473yftvVeOzIU8UCYTSH907SjYes85SwpyB2KV1bSaayx0juBrCfFnonuwe4/y1AVdciqsMuIPQl2aDK5w3390Lrm4uIeSpA1ENOjt0S+RBk6i9+h6Shank1Pmd7xAHz2mNJvhW302Wh03uaFL+s7LUDZmVbKI0k/4kye81kQu3HdF6eb1e7M9yb9Pc13qbcfifuCtKMCAndJB60zE8Q7+miZMfxiINQT6LWF47WptGt00XpIrnKH/RraU/gxH9/bEgfnCmWQTo9NRKKF1VDyYVkaGaaLnlX6q81/OgkgxU5+w9eJPhMdAw9WVV6BGJYBLu7AJz42V428wjNdRyfSNOa3y+wLKXAmONsGuulAp29fAYGq+GMFnU
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
