---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgA2e2jCTIj/HMgRzNdSnYnqtjKLuhJ2PXQLNkVnSJ/QXH+6OfM7tbCneTKBjMpF5injBewm3nUD/SYQbsg/Q6fuhhZbmAtf6wIt0pPYHseD2FrMyvQeNkMxD/qKKDbQsmtJN1We/bgB3rvj7p0kKqV//OmaGj6wHM8WKB0Wnc6e1eWjZ7nuB5Lh74JtZn75XqZPIz84ep9djzBYJXYE+kWlRqMnj4UOTlVXIiKDIAurPMNeonWi5SeTjcZWSXGXgQq2Gia/G1BbjjqAsalOfFpKgMctJf6+ErylNjBsxNP0bAjNQoSNumbKGAX+N4UV2VBEaNbnr3fMINcgrzessxTIold7tFlev8IL5kFOilhbHpKlqDepAdFLeqI1RuuH+hA9Jk7/1beu2A1R/Gf1gIsqGPE1peA+GjnRfE24r/MvZNNzOublnGfRqlzGeU+koFr8VO+WndIFps1pknrDJj/CgttLj9VNHhIiahqjEnuak34jpPM0dzFIme6+jW8JkvqGXmG/g1z2w+Rl00KhI4zwTcsBNT1ITys7mDKy4UEP3w5hsvfAVViOfGQCYDPFF/mjf0w3xC6mvryQs45smmU9cdAMRIf1M6s1g/4Nw+UJr+ZzhZOg7JKPMXCLGUG/whcc95NYeLn1vO0pinywqmLEBeKoGOyE8DYHhNp5ASEUvbDrKycRQdtuYXcJZXwET4pQFfAPfrGUf1wFvlcQulA33jjZp+vsd53KErJ1Q7gRBasd1qo+Sx4psoqcSuzKAly3rvsT/j34orGFQZM8j5R+
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
