---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBqvpKIbtXRD9EeMd98MV9ZXAmtz2sis5KQetTEiE/Tjoh01C/FrQ95ENTNUFuMNftQHw/fNOqbUt5igbxPnn2jD2ifm0YnRNatSi0IVIM2BB6DUE8MZPHo05e/mR/CogDsD6K2FRjMJrQOrq/NC19CWVZGoPBuUNlRzi7wIWAgBR+M5PKh+DMs8VB+PxY0mSPW+6SBWblDPGfbBrb6QSpDf3bKzvV7wDgIdFy2lP/z9GTUw8mWaI6YqJ2G3jpf90vd0+ki0ci9RGXN4BNdiFox8e+xXR6VA6qdIeaT7s5dFYwUGHfVbMSC4buqFdIPFJOO7KTLXHXGKUyAyqp6NtISX/wxnEO8fWdV7tuEsu/aDitcsZFuPwRUMJkDz41rEy0m4+bk2jslSwKDWuMBVyoSbl+FNDPqsDPyAY9U3fBnj3oBm7R5DgW8A3VGm/sA20gV2KTFE4SUKpy9qfBQQRAvdUbKH0D3BWUFOxnpbZJQ6RIJ0wB4ODUOIcCTEvaaglnm0PsAQc6mr1an+MNxzOFNsc3QowfnvcU1RCh1tzlSLWjsTRrm/vgaE3a3QtNfGtJv2t075YSvMqZNk/aa48h77j9XuLHB4N2RMYUcYKtZin/YWCYnSVxurXYf2wNk8kkYtj7fFzxd9pmmBAdEzM8cjGxMJv60pBBO2GeLBJGT+yewj4LuWQICSQUk7/+FKgW6ngUB/wMtfepX4y8qjSgqXM+UaqcnDKAMSXHd+QxwSUiFsWsrme7jSmlhe49cNrCMFCDuV5qs9XESoKjL7yEP
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
