---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgACpfkL3USZ6C+VRd1ofDlFaRQ5yKq7X+45Ajg2jTYXOjaj993VOiGEpetWbYnqA0hZPlc5El8PSvX3lyH+xc8caQHBaike84M2kIrHadj5//E8BTk995EI1ziRsNPvQyx8fbaWr/ueCCEIawNEhSNfTqtr17UyBNdVWtwdL4Ysk1v0aK36rA1Aq0G4YECGKWMdL9PKarX0RugH+VlZtGXQsByB8W8M213ee7DMcJDtODS9X/EW0QmngXDMpNGZDkLdMIH2rKpZxMW5lE6MfBEv2lsgQT9uZXbQDHPQWiIFrWauEZLdeHzY27S7eujgn8SZ5G8V5aAWvdRSTFxzRpul1fYSEJtwFVPDc7RI+Fa/5VP/lGZDSWfqcZGw4ndhoIkzxEODzNIrKwyDq36pmpQKiCGqTG4V5XYVr6DK86m7xfxMh7HMHzCkRvrHmLrsZhezdcr7iZppCm6kZfEvTuolVd+ou7t7Bifa4+d50j4B85ZWS8tC1YoBBkkIjsBTYHShN/fDGFdic324kNpjU75hvy8x9zow7JEm0ivhdaIGdeaFe6laoNCVpiCW6ilgDm5u3GNLlH4XbNwIne8sP9prla7XBPS0yVFIaR7EKg4ik3EuAUmG36OmL0pGVZEcJqiFtF/FwDucyN6+SDNXoy0/pN5mI4lqmbOg3sOzkGKKf80dNaVYUNiYrhL2fDJsPKCjbKwP8unMMe+6k1tUvHUSqPW2CncMpg88lyvPrnLevrZ/Kml8F8ftaRHHo8PHWZqXsr6f7hIUu16U4b5YuC82
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
