apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCqlEFCl81R7lCfffyAl6bgs5m5q8xge0O7UGyw7yBooRRP/Ps9EOmqvmYClQsFAK1i7RucZaWNq4Kz/XLPGP59lOUqOJeoPtK8Ih/Pex6wHGYjPwXjFoywNekkXbyi+BuXWr/Skond1CbR3bIdzcRFHOALKwA5xveHZccyW27kqE0yHej+WVhpO/dAvHjF7pszjiamqaLFxvaZmoj4+D9M8oI3jd+jS3hwvrsifYWHDzbuM/nctV+uVE2zlX1aCh+kSWD/b34LtXv9sz2uX+JKwisC3aSV8RrwKuTxMoYIzxA5l44xyO0cSyQgwHTNMMUhA9YIZFtmPX5SvwLQJEftJ0apUenGBm2TKUHoe6k/XdizCDN+K5uVTIH1xo/ITk0kLgtsgw5L8zcaS1ySJoPEInAbvxstVFALNyWKvkFcEHFGo5/aeC19TRONIr2R96oV67tNbvFEfGKcxkUQTP+uH+f/wzttKpPX59O7q4+hyRPOzKQ3wpAr+XsVzOfleeMG8Cm6sRdIAg4u4YLiw93soSV8ZSGQAZZBdIg/Rap/QJxdfPwnKLB4M700/rdvrDbDwq9m4ciDgfRR/8GBEYcQ/fDxlPQY8wPF8L/r3AG3Ud95fBxWSAVYjKYXJB3wfxXobpAe+j0WqBifOxqGM/Ix9hROi+nsVqfZaVqkBvlxvXmAm89cxbfD83Ls24F9Tqz8cheudS3bwLZmBDdLCR5xW1/RNmbP5Y4MXcj1DFAmlf8pt5eouTADQoBkDQd/vcO1/JkKpauSC59cT1Xoh28f
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

