apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgClyKznzFtrEKPGy1IR6RK+BTTaRwZ2H002SVWyRe/yNfiTUV6fPe83SRNQS2iWsodh5QmJsqB+VSy7uashcG026Do+QVPmdxVhDDdy27oUo+vKaaDKWGPsOrGAGDYVn8vSsECXVFQNvvk6FZ26/SaISEOQh6FVY1lRyiLTTDQ2/oQhoXCMOoWgC1K4AnD9zL+3bmFUe85tEFlZNwJ3dJXL1rpzeU2jntmCszXV76Z6/CJlF5yxyApO+IHhjjzidjycFuuEQo9cVgaLdl7A/Xz9m0+0jfRwjAHfH2hyQvUYhY8wm2K8gpw56XBVvtyMI2YP1rBOra2Rxd20RAtBpQgAC0o+qxZZf3JvwKTD4XMQsoFfn646BFK59Kk7bYs9Mv2+EAvJfUNGw4fH4KC+8P7jO0CIbtgOvjL6ZyhcnEdRPGTjqVWGdCQX3WuABXBMIuj0swMh1SV6ZEUIvxIRCo/g8ACejSl0uskaIa1FY7JT1KdYWiQXgP8zcal6vxaZAd1L6PHA8qEkeqx9s4VcL8EOcqwU7h31oD6PrH4Cfb9Gv7xd+WmKEAWvQNNQBZ2E4ABjdc5SYSNWf3QN2NqOhU/9HSeaHWaxiQNGRiEGik4bJC+SHBkO5GT+7Ry4HmjDqGiWoaC1Iels99ruka5E0vLAKcT+cWwifN6DYHUeWROW/rfFo/ftcEkpd0yM7D9rgdbGA1le/e757l42P39VVCXFicVxdwEAFGteAPDdPoQR72qEai4KEdOz2MMh8ZfD9YWhqGtdPV7l/IoKota5MAHv
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

