apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAZwJgZUG3eU5ay0BI0FAPxEbFwfSohIhyuLUDwM+AuP5Fxh+h0a7xVevbM7S6tZchogpWwRVqXYvmpU3hV+DPHdrlrXoHj5fxaSPv3Jn4k7qzJ7BEWja8uDXXayQ2MfXyDsgORIo9WyonsLHz1HMyq0Hn2/4UMRlO4SDarQKwNObDHdrqGyiTlstLsg8YqxMuTvOjEXhdZzM4fpJWCoe9yiBdHcD1AmmdTIGliV39kr3DR9PdSanlrb2OuzxrIqQTQKDJVSRjCHZF/HISGWX45QW20t6IKxOFMQsN/w0Y+woSmrvBbBCaTepZyXloAHY8bz8iD3iDwsA1hDeEv6Nqsoju6erbwd5toljw3OmwP+EoCCec/+vSoIdsyFarmPOE/RFGlRlheJQzDyuIrccOS2iUEnBQAKjfPgvCKXmHI36kTaq+sJmRRtfnMXY3AnKp0xEXBbe/pDyf9c1JYcA7Xus35oH/XpBCS9YPG3gkZaVcwU4eWfMiBSxHbahkLJhd15H5fCBKlk6xyS0+Ssrl7x2NZQyMnQTzAhrcDfgaGKY/Wgr+NdBb7u+ZtEeqRKIfOzcJfEhLWt4E9kDf8C8sHURSO8XHYS1a/5vNIPH81VI9qcvdcp1ujE2TTQC8k6BbyrTu5sx1zf1CEss+PKqKCk9iap6ofxaYlZ6ClqHXVR4W+g4GIMGwlO5dxD3i2jF+EhCAnIyT/yihYmf9i5sDZF/c1wGWOkDKyuKN7S++gHk9GkqXjz2E+gdcfCXk1eu5Frypz2E5cxzf9a+uJIFWz
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

