apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgDHMNlcONrFzDt6u7mlPKz/RRaFBaROoZLdUDuK8FiqHXe4NtIow6Y3lSBhOevT8wTLEUIiF/JCyu7hg3gokLjlf38Qq35tzog4Vcl/VNygzjXciVrzWRxXUqdMDcRpipxGR0JwFLd93oYGtE35POIZ8GLAtwJpBykZwiKmhBf2y7IlWCdswsc4nwwwSJro51iNpAqScjtcEVjubT7FadEixXvvbFrB95qjvVYAUm3sG2+VUOus5EEDHOFut0K2Sg4jjE7cVGerpyJFX0JhGbAuEiWty1PN88TK+RJNj90MVPDxuUG8HWkQ98dIb1pahHiR5XCnrUGsWoG8BFegRjMewIfaznmYWyQUdGvMqBGDxc/c6k6mIte3a2cJbx/waOP6hAgvrFbBG7nb3cz0oGb5ZSmq9MXOdOrIyJTON/k26NAvACzYudKXB6JCpNrPtJeeADkI5SfS4rwKva/WlhLMefCuN+JIGBfuhZHe8MGULMuEQe32aWgZHMV9i4iiMRsIqi9pwDiljxO1ZBlE0PbDhDHR+fwqHNt/EMcPx0+Wn3TAQ9Z8PbmD+mkIEzZjdjIFLxZhiveL2DRc2/x6BvmMNEG4LxbAynMLweZAtXx1z+a8fYM8dPhjfaLgGggLl3r4lEw02vBcaQJeCPHsXF6Msm2AxQ11s7UrwfCm8d9+163s5cPdmtHwp9R3gNr00axynhMgXhD8/+wiI44d23tBLl27J9HpN16u0/Iue4tfIfaz0mmx7J1Oz5xEP34P/q5CI5yVcfho6KeIpCT83jS4
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

