apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBdLr9sqch/+1l17FIY2XQnzheBq5lANhrDkxOsik2lRkXOH9c3V6NUZX+nnYomj56sD83DWO2D5AHc0Weyj7aczPa4uedktojRHi2x4wTK25jYu8uQkE+OE0kIPFJg2Kxmd2824PFIGB5SOWAM532+/b8McKk7AKdkSTGgPvCLeaByhAbLpkUB7YxBK6k7TrmAVYg/EFMbrdbSpvIjDkjZqMIEEsKRXNw+CACzr+KhgR+ZvEGLxVDmeSf7PIMbxzOzoq/f0WpQC8mr6KuzmT4pV8zXRHCOBAmYt1xIV6b2j3Le86SBSfrVQw0LFe4Qr6opeGrvW/8Glw+5OWsZD3irF1ugLdJA5+bjIhtca8uXbXfv4beIH5Psj6ikhx2TTGVDPUBHfp/5mkSMWPCdRblFDB4j/xq+kBXfI+fehF0HS66eQL7QoCbScRdcGxfuXNY0BPwR+ov+Z7mS1oM4TWI0m2TsPaLZJVpWWM8WmrtirkuU+jb/NIuuz5Idb7MYU79I+PEx4tjvf1RBSvG2KeyLohBC1SfPfxtq7dysBSBd+dK0YuyN4FCKwBSL8R1m9WB2ao3CEfvKkZ4Q0QvCNnnq9akrpOFXEbAXcdXN/5B+mb9mBNZOM2ZXMv5UXxdRMEe8aSpPAIMm9tX4LuP4uTTTcWbs9hu0FqKjBi5X3XHOGlZ8OTp+6xqzJMt8iKaaWF1ZhFZ/x5Kvpl2sVBzAM1c3E5eSYmii3JVZagMWBjtPoT5m0or2gAb1cFH4332lwza3XX3X69YTp/yO8wOu2+Rm
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

