apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCmVh2oexmAF9nBogb7rpQiiZyvPvkiIY3nM0F1oD2LA0KSBUWZF28vL0co00Al6C1JLvdH+vdCj+dFDv4C9Mkix3sWNkBtd/MTy09YlUT/RDLIUpauUcuQO3wozy6h0G0wFlRIXEPdmetGgYXOY2pnYsXrwqt4VB9OOAHVAHwqZMLO7tsQjEUyr/hzPdnpcs+TupLp85SwOVuoemNc2C+EZmoC9pbb+5b9hRaGhgMtZLSIVg5ZrhWftaDFvDlkpt+gZ6utKorM1mZXaU/ICHG0fUJsfFEWksO51FfkAeQxUY3Kruz1vwLoxeKNVn/WvED12H9T8oBj8To2gEueNXh8OzdmBh4qtCt5+JGyGlPb3jYYnTPu/P0czVrCK4GjvbOr3Lc7i+c74hkr+eSRnVJGiwWo2Gc/djnoe6q2+a+clgQWBsrsMmgtdoehL82+3Cw5ZUWxnG6plE71pPI9YZMlUK+HX7C9VnRc2PaJ01dG4+9IhjceeROnWkFtyn5E+rJVA0EazhPiD5+dEmvd8IKuz8Xd+xhi5JuBn0UbYG2llxQ+7LX2CkjuUKLV7DVBnZ68bBQHN3K7qVs7GtQIA0gQVuSnly3X8irCphL2DnAeVVNzfWmZZsl3tXmfF20m7BAqvvNnceSOiPAmML1KQZN1bmGcw2GWRjAL+r3xYYHOqftcH7dLsYinkcH6zBf4mBQZ+gj0BKJa+6jSIVEabB10OQi+zkL8SAE5xCmWS2XKTBgWsDbigOx4smA+dP4edioNF1wc2NLqsAiENKoCGSSH
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

