apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCmlwwb52UZJASuqB5NX2RxpQaYeJZ5G4B76bZjkhCgH4adjruT7k9v2SWFa+dLQu5ufCTRbqV+rdYVP9rqS4DdZ4lrRsnp2eyeQEFPZ/y7CEOXZ/PmYcfrMEiIRON4oaBcng0GIqBtVtJ4pZJH2Y3pgaxPMJKFuqRmyT/YEYkEV1QYhemqBGDWZy/OLzuEqtkqpu4o+8cO7BZK6M92dAGpCymc6WL9U1Thgpl4sIvM3GjT4G4CUpd6AcUcZYbTvTO2oUs3o5SrHQz6qfi53Q+WlXKSV+Qf62dwrdKMA8Gp2z0Wjdn3n9qeYZylhtN8Sdnez9VEP4NnpP4r+REGmxfdM0xWn/L9Ajt0iX2SYOE4uwXk1G1gfZ/6Q+OB6vZotpV4oczUUxL3yujtB2uR+ERfmzy3vYSzI3Z1Uywt1cZMgFTCfafjRMCazu9ulJdWj2kQA4Tjjctd8R/LF4k4xX2wxk36Gdcs1Ee+QcFegLX+/5y972O23t4aN4OszE6Ca904DMAM+cCGzYMS1alZKwtEb3HNSpXJJazbAeE1SiGKwThM88OV5mCxDqlD7QK2AyMPgS6ASMyoVT9+qT+L7p+XM7EwlLiWxo0KmVv8JYdXlbNhS9Dd2Em8JJ+GVErPXt72g1wufLHMS3RbB5TJWwkQ31SbHrzyQUrxV+Ouki+TlDOd/5E0fl+Jjn1pY3U+heoRPCHbGWrb3ZnpbSV7XaxGPK2W0ObyvvcSto41I4bmUVbWqjWLDQnk3UU32/H8MdUo9Do2s1g260MIJEY5gkym
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

