apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAXgkYTAnBW0GzaYtUURWa+eZcB8V3nDPfAW7PThyZtFcuapGko2fV++X0U4GcZA/eZw1CNBZPJXliQQaS4qPHNw0Mbu+xQzJ4pEMnxl4r7V27NjxPYdDXe+IbUCCC3XJLj9OOjLkPX1Mtr5Ulg3lVTmpsH99XLGN8jHycSD6YKL3QCDsrmt0x1fRulVVg5l0Fh3kDwbX/iIhcEwRyrsaY9ZxKc2LTeCoHnlIaLZMATnGpZPFse/K4ATXrlGSPb0pED8JdnBzOnKW3SGdlIZ8B7NT670U80+P8EnZzIxFjXiRXJ+aqkjiPiZHAVtFGENfEJYsGagVmr1GFp8rZ3WQAnq0A3oxwtXC5NoqVoVNM6+gwiGMVwE5rAsfarNCwbZywp3zh6y33BbWMBtrIFcxmGjCjhRGaRyblLCRieFdMWxOJy0ASJenbosAYYg7FLgoZtARKCN/CVLVMN42LJVOKy4CICDbBWbh7b8VjLY6EhNAwcn1+Kj4H7xiGsKxZRBolFnU+lBKzbcFREBaWksNWUD/UuEZ5YMqCM/bcGIzWIRx/+Q5RC+8o4e1gu2k/Qs1y8rdlhvuBsB1fRwaz7ZwWy9Z6iAHpNVtnF2odvBeuBuW7+fJ8O7gi77BhlEO8u5TMPXHOLXKhXfx70OY3FmnNJrz9OFImHjsyqe+xs94nhtIngefYJT7cvqQ06tB5G+HhjG6sc+oEI+b3+XEA3+Q68txKelw4On/Eyfd5wuMHljemCieRb4y/IIj5U+W5UXArn32bvkmO8WJn/x8+Z+l7H
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

