apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCQ2lWsmRQDfJ8i6Qv9SXw4FtoYuFAHSOk1ofp2fdD+8k7YjxFyUmw3IOoD6JCpeihsFISybE9MyjrvTpJ53IOqHxmGqH6O29EmkwiQpsR8SW3uMfuDCgviYF0bBinuP4K74R/8DXGwI9N2OccrMDRz9lULZKlWwZW3qcLd1OuthZ1mhYBXRewFCBHzTOewpqv0sADmmYm9ul2ezH3XwTCuu/iyLk7TY/dDZeUqMpGbFWW8b8zrkqe+jjRbj7Ln1ivooLenFzpDTM9xXxpNrmJ4JvNl/Fpxa27e/tklFGlF7++iC0RbuDmX3tKbKWZTFr9XE0RLCxvIXKWUHwySEfsF0nOECZZDyxIXgQV6T1Uu4y8rNcdZHds+4aPxmLZ328nvuC8gVFKBZX7udr3rR4EUGxiGee3THp3MAfPAweBBTSAykGEQnNhdfmGEo/6l1RlGGgpqsDAgD8rJNTES0dlJ/i/4crFPs0/6GauB5WxgZOVvT84SYo5OvEnuPpGXl6E2SRRhIS1mQOKyzqvvZOFqOz+nP+WArGtJG73R4dDpHanNx+1DRssjJg2tDqVKxjIPkM4LcRHSZxMkQ52X72JasVyiJ7OW5BmJruOQy6fYWeEcMm4BIGNMzCZPw75V73Rh1Oy14MYvb8a97SW8yleadG/pgNxTabB1IuhIqGbMJr5aDFvtjvS2P/lZKY3Mb9iq4hFKL71lpyabh9NyAj20T5uEFZysEJivTZR9SsNTdFtPtHJv7Uq0Cm59ZHy9uji1oEnzz5jF7c2G16Mdq60h
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

