apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCy5NHpeJDjG0/pgG3BhQ1t0hJXqs1bWMalXi3oqzjZ/nsT6gRAM9Wl1SgMiHz3fiF/hcel55VRgH5mLZVNRD5codn6UBD29O/2htuuBBUKsHJlqaI5YaGUIQt4fn4/DIWjFe4QUvV9KxFWsDWx4Li7Alo6dGgkCCd25xEk7GPGGBMKrok66OPP6SaxtOaA64754tEemOrljCSFJtAkmnEl9ObiQYQXG7AKLXznOlP4B/Q1r9xv/ZGjIpZopfl7xz2f54DQV13c9ymBvv6hyOhdZNgCelcad8CL9julr+74wjO1HSE1XrcwwIs20iGNQsMOVEJ4fVYSvKBbXIcl+4yFL5R2OBYB4piwtoi/WqI/ll71bPBgQpVIyf5wPb75WpzQerDs+SSMaWH0t0LoHoXYiM1s6BFQyf9c74NVsDwI69Se15COHeEOTtMieGG/QXhYJZun6Dh8CHnhGM6g46hxqeDCgR3EbIJwBS0g/gQ95w2kcTo5OGDfSL0D8wpl4/USI4BjLEhw1uL/ury8VTJC0YrtSCxtJ/F+RHworljN5QCgKN/Y2a8L9Y8Ahcl+S4qtgSKTp2XA25R8gcybG6MiTNrnVHspPdH/3UuuEKij3L9NQIGedeUXTIaN4ltmHdenfKpJXd24TYKh8SuF9+YrE/CLzMgcBJk2BhE0eP2bRM/xYGZFx0eWvSJEZzq5SYeC1+xlx183LFPxRY5mrkW3O0t5vMu+7EpLY9cY6gI5t1qGv6Vq0v21lld7rt/hnbiSyQF8r5DkmtBuRDi1y0Gj
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

