apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCLQK09+bJYKzijuGhi3ZfcFexK9yZWf8jCRzeIfCiUrocv8V4Vv0w08uOQeigcnDz261H3wD74xWwzLwGdZf9Aqc3VwBVv5t3M9Z2BH+yu2J+Z5mm/Aol1FCwxVnx9e0hqnaWHcU9xBnp/kCWDtvT+N8n0Nmf4c2jRB20yeJfxqMwVwPjYdr9wZUemEtQRhuAexU6jc1zBxL/OrmdUA+B58brtkjcjpMTNHIpXivTYzvU0h4+7nPuq4CWTBUhBQRPWYIDR9qbyz+Gj8UJlC3hrO03ZV9/TjmCZ0to2K7cGHDabGFs7GzfLcPX5x5hCk35yllHdF16XbDWTCHfmbr96twhvKGFA/jzflL32A/VaFR8PuxB56sCWyL4C+CfZm4IjdRTh5/sP80e/tnysMyoRrXzhQPL3qoWG0tEKvqhu3C1aNC5MR3BVpH4sMwyhugruWnSkLB/Lz7gdl9NkzgyD47EFLoQLHHJN1nuuw59WtQWZIc9s95mqR9zlaINxKvTTYLlgm60OwvwhYjOtB3NGsrgnK76cRi9SDi8aB1Wri1/Pb8Fo9/xGp7e9lM4AAgKetcV/aOEkT/fPj8BSm2AnG44/jHi4JjZ7hxUIXJcVhUK1pxZa40l2iQe81mB71iTClgXGFpWq/9Wxe3YvYMNlHfjrHUpkSRf25bltUftp9HbOIAItqcl0lQDAou5LW4VZ23rOQnl+zJX1QxAYGO+kmNc30p8GQfFq8ij1ptSR3Kzvyw7vCWkIvy5bn6o3QaSLnWscm/lN1HM0CU9lONMH
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

