global:
  clusterName: hcloud-vpn101
  kubernetes:
    version: v1.34.7
  kubeaid:
    repo: git@github.com:Obmondo/KubeAid.git
  kubeaidConfig:
    repo: git@github.com:sbdtu5498/kubeaid-config.git
  additionalUsers: 
    []
provider:
  hetzner: true

hetzner:
  mode: hcloud

  sshKeyPair:
    name: private
  hcloud:
    zone: eu-central
    imageName: ubuntu-24.04
    cidrBlock: 10.0.0.0/16
    subnetCidrBlock: 10.0.0.0/24

  controlPlane:
    regions: 
      - hel1

    

    
    hcloud: 
      machineType: cax21
      replicas: 1
      loadBalancer:
        enabled: true
        region: hel1

  nodeGroups: 
    hcloud: []
    bareMetal: []
