---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCBDJOC/IVeSw/0NsYAj/ajlwcT2hKk3O5p3TECecD7/K6VsODweSMh/OlZrW8+k+LkvsW0IGLnZtE6fFBAaDDSW3caqY6JrxBHKjqmXVZ82wAkwxtGZgc6cDGKqTmSTszMI/Hlxaq1sCFuzKDm3lnkho1TIh9NDyb1phkSQIeoIDgG12IKTw3BRQCXL58SgDSS8ttKnxtRsNW0oCnZ5kfp6TmNbhLo1N68PcsNch1gg0CHqtEu9zAfUWC2JCJDMOtB9HBodXL1pYa3BJ28kholTe3tMBuvxDDFF+pIxLacXPoWnXzuQBJBrk3yw97DsQd842eSMuo4aNxmPGQZbfQKk5o5yTAaCzX0yWkAR9tP/XvIE1rJ/bFX1Sj/8npR6zYEGh2xMTvxpkBuNB1PGZHM/I4m2DKgG13ca0MpQANp7w6n1XAj9TjrMsq5LS5fRsJ/7opHXg7qbVzkCOQBMgQx3p0t8R1RkfuBsu6HUFYVyR1EMMXYkp5PermayJGI5LQR3qLA0sYENmVvNILEuY9H5yOmZx3wKP6hXkTABG5a1f+ibdB6whZl35yfxtYx0uBXc6vz1y2idrqFX3QM0Ni9hfTlSXr+WAUo4zRU7LzhZ3jmuBvdDRlhPJRD9FXHTEWwdmYRkhLdVifSfwv6UuMkVTm67vB8oDNedkmJrswRqSfFalak9EOKz1xQDlVm1Y3CafUB8I6rZWyLmHcmT7sRWpGCIGRn80On58weIpYxpKGlPuS/8Aa3eeeXOzyPmjZFtcwlDB9Z4QA9QK79f27w
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
