---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBRYrDak+PT2waKWRDiV+addmfkzl6kcvXOnRXsQXThZTI6x9lRyQd8jjy+/zq9h6u6tkG/vH8tn2NoFndv1HXTks5TWiiRWdufBuQBu+HxSt8MS+yCAC+z5cDUAveg3Upuio0/Br9AczxT/zJNRIA8ducFoMNFjvZQ4ml05VpTNf7az4Otu3cKy1a0vrFmi+pfL9WLX3NTG/d5J2BSWz6nVFYA5SWHq58nwZC2+4HHYKZFj/xXGSwdBXWbaei6w45VKgUHs204ZUB+1ObdQRqnTY/7SYI4ryQdEcRil17jT2DI5moMhW/KjxVq2Nzp8r4YDPOL9IAKXtcj2K0l01Z6j8zdfJaRXxBZRsNAeYJ1m2EWo8fZ2kR8ktO+1oL+oti9voMFPlLrgVEYWpVGytq8Hh6230pdDJaXp1DDC6o9V6/q9aFWkc5eVvG9H9Spqmpod5DTfY/7fET8dASxxV6cVvodrwXbPoWYlT7zN0zWii7dd3jgTJ4CAb4D4kR1lnHxbPUscF8ZI4SrTaQe++E4IVoLJWFPUMz1HhnWXj8pP7NiPXLNyRrr7J8VWrZ8vK0KAFtnwEA6fsVVmyp9BG2mNqzNJJo9lOl7bau++VbnXSz2WqZpL0qbNtRqzcggZFDQKDt/LRFmDAKCmVEiUOyHiIOPgWhkpOwBJ5tIadsIOoM7+vixqYqH6i3S/RjezinofucwkZRrfnVweyLLamCkJzFf2aJJjvo02oLrx/Dxbs+lO9Exb+QO/tmyQvf9nNSjjqdMPzhgGKFWc8csJLTF
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
