---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAPLNuxyCE7RodfPoVQx4qytLH88gj/HBvRPGmZkWuhCeqTwKvwxTJ/aqYaAXt2Nf/d2d/VG8lG0EzJxDeJTtlGBLR3dBNI9minK0Ir61IGIfjqwL7gYjNegjUQZEw/OPXewmRyvpVTySyyHj9t19jWgkgmFpoPWrc38+sETaLGmEnHEq8sooHaMp/l4SghCHMgEzLPVWFZZ6oRW+GTXWcS1PCimWUMG5xnqVux3vePt3a0aMRdB0bqDmHKsgZB4G02G3EPvQYOGzc5LDJ34mHT2ykFwttC/Ur111OSC1cF3bDY7F/loxXVUH84lxHQ+YRF12v6edFtPp0JP6mAwtz83fC70zv3WFzCZt2PxzPtGyhMvEcZND8DhN1kk4USiK6ZgS0rSqNi3w4T5LOHhwCxCts/42PPPSAL6M6GfGIneLyk6msKDRnFyXdhi1NoCsvNAMA8Hutaa0BasMHsv25w7yaDapomzTKOlP4gzAU8VIJFw7RvkGkuM6NtUKbDNe5e9wL0CiPnmBXs7PQfMJhSRoLR/UA1XEEBwnBTi0Yt/T38Reu/8c1INGFON4GdbNKWRctEQ10pP0KYgldZoEiCdzkt75C7f4fS+1JBtcn8CZ1800QPThttPnAC4bOXJZ21UsCgvvk78Puy1M/iFA3I7Lk3b0lmt3Ad13dhxP7bL6B/Y1QtTaDUVRdODQxNp3ygrdwtxOBrqztI2GUvR4f5Un8mEEJBFr6kXtuXet2gKtD7nI/rJr1djo1Qo33o+0/jkoeokJM2RrSgHkzNVYLM
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
