---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgB/jXYLDLoPEtDMK4mI5+bJRNbwPqn0o/HtCMLU+rPCMuopjiy/ojdWIJ+BVQyZmbYaEyP3KqbJuHGbtlFXe6TEb4y5wMyJI5bNPLkSpLZAwrMgZmrNz9W60x5vw52OI1R/u0I6hTXam2V5YE0XLhqkfz+mvPaoqr/l3Enlz4JvItyMBXXMoYZqG5pXzOgxO76iTC88M/0Fo2JxngWwMU/i/5U97gZigdORjYIkoh/k0Nruq6ankf/K0Q8qOG1K2hJvrAH0o8WN74z+8VNlyVwwaODO2Mb1TYa7YSwAXzmdcDH1Qul6P2PTktQWPlogbYAG6EwXWbphAcL7tvuW485i8ZsOiW10r1JTFzF1NCS/ejmToEWzpDBZk+jK0imJpd7THQHLkymDe+vrzIbbfOrfporb82R+oPnyS7J64BTgIdo7D8QRgMOnpPy2igFvQGI1gR6gyg338MQOuymwI2pXQJnBUv+3OPj2ZagKbGRtD4tJE2S9TuOZaEocG0h8eMsS9FiRoyWFRXkisMTK43KVw5VJglFIjGe6BjmOJcPR5vAMs+2MSRoDd/qLBwDVbgfEOAhTj6o6sfQf5j7FlWv6juyibjiUR834Q0li+W7slcXgOliFAQJkoT/JlF/k1SEzWzXh47fC/zaVX/pPNr6cbkfz/crq/mxmukDwYu5DI5KD8Yx5wUkG+uYJQMbQX6rSih/Z/RsOSuHjGBwlwncceXQkAtaUDecZ8Tt+KrXSwnsKZ6u0WVG2CDMwtmjhaJyj0jQddu7rdTdxXs7MosN6
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
