---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCnAgQgmZSITOuptDTNQHMcbtZTZmaB6tNZTAw3zGlSYbwtt6gNq8n2/rSTH3rf49XRNJFeXZxe9xZ8usjdF/bAn2BSSM+hZgzR39QtfTfZ2Z2llAJvheVeojsODLHcyad/nUcT0nkkjJ2fZuVkpOrDZVN0m074v0Z/ElquUjmO/JXRwfjbf7dqRVFzkBTm/gUqtLkPmt+OJTOLKl0yh8nI9vAisOn2QhWAU/F2fvXHx7PLV8OBAYbNvDPQlcTXeDiz80NRj3KtPwiR3ZP21XcYDFctPjT8cktxmpAEoIHh/boyb0hPyXjRXDWff9pAJOxlpqmSnqoi7h65CnFW+ElevSfr0B1U/FMylIRzuMBdFV5oAlHM2sSBOE0+Am9ZHYHaGlJ/PsvPgT2J5v0q3VXw6jV35oqOQSV1KfPFBeOkKt7uvAimfe4mxaHGWxmJaNQCqLIIfJyEszBiUYakvQ5V9AT5qiBLI+5zNN1KHpko2L7qEqQiR8OWAO7F+w+ZkfiOSI7Za5NLYHuRBNZ8rjlf/SwpyMr2FcJRvBW206I0myvVG6KTOcKLLMOnxFV/3scpf3P/kHKOTKc4Vbd4kLndRd3qmcPuamOxwCKiqrJUhCNqHOkIbaEba/DePalqRd6zSDIR3hBuYorUJW7sCmFXgdVbjWGOtxZI004L3JBLY1jaiUO7L8MdcmuAPZqpbyysnmrwqfcD3zqozDYDo23Ui0GOpUJTPgsLYpMVTZvDUNe0+YePcdik+lA8C6qUDc9GEWWnOEknwg1KwlaHtW0f
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
