apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBfYgXhvu8G8fEqixclGnCVN4Tg1C/fBmjv8d7SsrAojw2Yh+RhRL7bAKD+BiwbCJKTtuqcMoUhUsHRuT/8BHi7Mq9GrPobfNTvT09fF//wH1rz/ZxHYP8igv6rrwTQOxt3F28Lbm3QTXQKnlHnoBzQLob8zfmVgSQ5sRm3ZZGtvlw1YzAv48+cJlBk6calcfs7VzVOVwiLb5euckabl+bYARZGHKKg8xrSXhpF/ay3cQb5n4EcHqdKdl5Y74GRHe4EX6IeN+J3VqyNrHjtK6xqIgRkAV2jCarU9eLCx25L+UNXgwFhKWo8KWbmWb87uen3PsDn1Ci8g8dX2FgfKvWRTv221hlPXCjvYREp6BZZNmDiZ3rY0axwwiyRprG2qwgEtHPqL1EZh6AP21iNYFKdtKnrTJXxDi35fWyhGXOIkOfv98imW3dsuyKMJC+gEAG2ixXTxzJQLR+6bpcSEcO6f/uQTEq//+c5R1y86U1rPKfvQ91Knd6a+jQtjXFP2ydXkgmXR+GpEiakBtyAIys1dKAwnbsrwNvlv5kfXgu+hp5o6oZht2RV+ND+UHYiheAsisE7jo1hsaYOPXF9o5rKCe6yX1LrTV4KIaLwDdrStcuALSAWrxRjWlDkkJw30ExAzmYyY4XBhs5NmN6r2V0ejgNbIWvZI9V4D/nE9XJeCUHeH75rghFzRv1SYa04Tou1+kzOkWqb5Usyp+dm3pzinAm4PUceoLy3hgenyaLAroSdmVmOk2rdArK7jdVnmntbPUon006tmlJQOMkAOkdw
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

