---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: netbird-turn-credentials
  namespace: netbird
spec:
  encryptedData:
    password: AgBgXVZdy49folqj/Aqxucyv6vgOcuBeteNsGa815JYTo490y6WSbfAhcb/xsOtrlGgSTeshE0a45XtWKiFV8h/gNyOkkbMtYChNIAiqdz9a5QffQY48VTWuDRmd+/1ghmKPSd2SmyFdqju75xcY7ipBF1MkJwpseAbeEuDY8QBpVsUMJj1APKfdZjdcdzqvthCktqRZqhGmwlUkD/6txxUErFvKvw5AcOYaf2NsKL1fR0o8dVC5JkqQna9DKJY8wus9g1P+JkLRWbhXEann1IrDicv4tLQXFJKje6eXEUKxvXnHZsPZw/7uwTySXKckcvM1D33e86YaVw+8cbJ8q1b+32FVW2m6NgilvQN1UTnKa34eNf2JvOJu0oYyvGfhWt1uid7tOrBy/mQKu7lQLSjyPutJafzaw9/YMZsryMoPt7CWdQRyR+Ru4yT/HqxMXcHJfpOA35vJ+c7RNwSyCO5usSJSWq0l/DP95eCmXHMB0uXVXkt9Of/7jzz6XypX76X+qT5xKU+/0T8ZzBKuPcep15QcOSg2Byt6nXeNfJ8UcmShzJlcmpHDXR7azbVB07ARvFt1X9hSs0RESHFhv27nApGhda7iWs0Iz9vJDA2M98OHwvjzapNrzu0f/nL4HIkIncfvyJMMpYeThhMCPfrE7TOmhQcIUrtoDSotrHNrLEdDtOBicc4/mF/76ehsHiamrqOMELNqh2wnJik5rkOUNBC0TYugbxVDhabjtMivwQ==
    username: AgCQyPqu4XAevEmE4PFWmVl+nX16vWOMrbDr7UxLdYkfL1nYibbGwz3APzMoJ4byAKPOR/FK+ioGmci9uO71l0M3fXK08EWkj0O32NOfOPxNlDeY4FhAneiatPOhvCefgodnPQrPML7FhjchyHo/0qfP5mvC3dNjy79SFEMAueusi4oSjOg6p49aGIzjqDYDowWJaecvoGbwLmm1Peq477+nJeoHihjRpmWiP69pziEXmlihOVsefVNl4OAJPlnrhYmgMA6g19KT/mcrn7yfK5U4e2hQ2B+gaXXsKiYbOS/DjT+UJa+Y5KaGmuyP0R1jTJsE8oyymupth+ZzeEmApk6uAUflCH2vTg3dXbEgnNSE4mdp2pRtlVMFkot5z/l7r+XwhU6PAM28BovZCErZglYt4smexoXiyZWJT0r7JkMI78bT4Uvddghc38SeZhphvz+XGN3FaQmGoSu/bDjM4pYDqviJrX/XMloVqrv2g/9nJInbIDZjOwaoosBr2b90RTnB4kZ+8yJbjvubUvgI/Q8U39fOi+rGWrefhtrN4J5kljsU7GHZfaRyLq5Jk6teRHMNcR1KYeMzFKpKMw/3BjHt74n812/1yBJHgscX7SLVQdRb7M7ACvaj2kr5IpaLK045W/GaXhhVY+CurvKkRhMu1qKP/OHbfwwvY4DXFUJTKtT7TwfZGlH5VYtpEGU9isKYByuzksE2
  template:
    metadata:
      creationTimestamp: null
      name: netbird-turn-credentials
      namespace: netbird
    type: Opaque
