apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "HEAD"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: k8s-configs
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: kubeaid
  source:
    repoURL: https://github.com/sbdtu5498/kubeaid-config
    path: k8s/kubeaid-demo-hetzner-hcloud-01/k8s-configs
    targetRevision: HEAD
    directory:
      recurse: true
