---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBR1xw/DRnuNHkXA+sa2xQi8hStO3IxHSJMg45S4ueVuMWa7H/PjzhaioFeeZprh00JBkXHKfQ382gsr5lOx3A1RGRAb8Nd853zyQmTE3IYEI7zCpUvtiOO2Wcug0fZ73geIgwd4Ph+T4Yb0NDgDrIvuoxO/Md/FUj68lLQh5aSX/UFMSCUviTmTjPt88mmTq+7LL0Y4064+EBK7WP5KmGd+vuwD22hZ9eT0swDZDKnj0Evn12+fIS9Ll3u3N+8TXkK7/HG8lJCQaPgad/FtNI8NTjCF0D3fLFCgIkNmMhH2bQ2C++6ZEP1pIQhr7EJLShvD8lP5q7KTHZ1hdgOwvOK+XtdzykH0xnGxvFGfRLGLtLFwyuKSdIz753Ua1LOOeSDjbpGPmxhjO5NznW4Kt9EOOgkOcPF/P5KQE2q+EKS1I9JXAnsHE62JoOJIZU7POmpiXtwB/5DKPJXkUt1IaMnOzcbG7yrXTJL1LgGHmHuLG7R15NQV9Qp2LgEiqvGb1z0bG2jgpgE/2YMownHyU8iUNvVRc2WWbiJ0tOMHR0Dcj6S7iYi1Bs6tEqmIeXkP9jnd7NV8v2RQCjgs+my7CvyPEQDjnOBTEMBPVQwp7kfqHKr82vHBZrPtXJUz29LlpPl4jKcjV2HsZzM210oYTqG8fSTk8DPHdQbfYy+j1Xa5QtvI29UuriKqpY+ScpxewNdD3Z5hb7BHr5IYdv8jYcaxA94wrup8RTPgKqsMS2LaN4eOMJWf+MTwHq8B89sSnk38Rw8ANgjXAqlfiheqzWi
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
