---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCwq25FMUlTikc4A1envPPNkoK4DW6WhebjncOir7hpz5NfFopmWvhPi+nGyMS8sNMOGBKHkyvHY8Nk/Tybrg2quth/qoq27uUu4OzdtvjuvlNw4gyB/eUCr2vDZG2tWg6R2FQ0IgXQ924NdpOgf8JWU0vAfCxDEABAESMCmypJCFLZgc2zf6+NfL5dapFAqb3Jf6cms00JZuGabYWJ+sCP34hpMixjEeyyy90lbcWKgDsKkgczDCDcNG3za12HocaKKRU9HOUehfBpvUh5DOxlZQ10P0vTP/OZ2jM0M9LLl9BBfoow0YVjH5TCRC+ui4Q/31cK5+K8AYi6LNh9rP1Vq1DWkRQSwWJHzRjukJN+QjI60+t3/D7UJTDbi8NPkPmN0YEFPGUnBwqBw3FPWw1yyd8GNGSFNN6DwD+55GUtHcYFQOWFqGwYjHT9n2pUn+CE3jNT/cVSR+mF5PEsW80br9CukMa0m/E2k19u13HLFzBDnN3LSxjZL3sN5LYexoU1SBttUB6L0q1pGOwSr8/Jf7aCIeH45+1g/1bi6eiqxKwjqvjFeaf6qX20iAa1Lg4QdJ/nOUYYWmSOMV5QlrrykD5srKU43EBCdHgjSs7TknGGTFt+R21s0IVDyrizUwh2ul/STdbHu1D0GhOmPvnxn5m/Nx7dzF9VP38rE7Xu7XDA4IGYy/aEpEJaJYTBCNBKdz5ZjkGcFa1YrWywiqNANWpkvtft+2bxMuaOIwZcL5CpEGlvavZmR3D+hmt/YyPbNin0qVCswJ+oBMVkswtB
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
