---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgB5ob2N9uDBuleeIgNLeh18aayn8OlWrAoNBMwAYwMLsdPVdFaCFQEDqCFXXD7SNvi98MIt01bKLHVIqU6YkrymARMVyTakBDuT5sYkO0PfzuOVF9zAz5db3r8Jb6lKck7jRMrVNAct78iV4TPvjNB6WHAm7FZ604NgmXW4RfxOqeAuaQ7oAlMmdqGoRPa8feqlIgfE7EV2YHFssqi+mixjePDAu9NwegASF0LLY7OMmXeV59X+zUUWNOrsO95wjRz/X9LGrmJgJ6RXohspIoys/D7Y+6cQQweobpjskfp8sSdlnXFhMMWZN80hInP73CGG1bP0+3A24E2A91q+UerfM5t+KXQTaKmXhcZCmaN0K+4ud7k8KgHtY6fYALv6HoP8C5hgO1z0RrzaKeifDoxH9eQOeUrL/MkE5TCPb/avEgLtLXS48S2hDkaczom8LxIOCzmfcF9lDkkR8M/MBA0CPkL8DV6PDPci97MSYTZYdSd5pN8dAj9VARiSdVYzxZH2zbL3GIN8XH4ZIiE8TxSiUJTzoXvjXuqJ/XbLWsy+ha73zQlAZaCi/sgE4zNMbNwqhaT15CjAak4lQfYy3T3dcfcYbFT+kcZ3zK0eJl3uGs0cIqtaw7U5peZcFd6u6WTiiUHybw8Cr6/MMq9Snf9W61V5UumbmJj5RC5sUjEk2XHYINKaMptwB5BnYXHCef06SuYtDy9k9jyK4XWeXMeH7PwZ/IlB6cpL2jKBNVFzx8gBYuUAFrINB69dlzU4IyaDMpL9ODixWjUv198OqEC2
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
