backup:
  image: ghcr.io/obmondo/backup-sealed-secrets-keys@sha256:21119359a94efdbf6ce81e8887e0ae35e9988d9e5ce0c485879ffc4f42aaf1ae
  provider: azure
  destinationContainer: qasealedsecretkeys
  azureStorageAccount: k8sqaaz1
  access_secret: backup-sealed-secrets-pod-env
