---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBBvv7mSiWM4OPub562GnOGmtjacaXscyhwxIk+ekCcwLGiXw29Hy+pxHxIy+o/7DimjCHmpUkGftyqTC2ZtSOhFDhdNOx6xRY7P4nRWbu62x3cb7SAkcEAyQOVxAWwfqjJcM4VvUByUcm42xZkOM0glYe0DIJlMunFDk/T7+i0GmkTKM+MNBpgIhL6Hgh8RygjYjRxOEjge4z+uCiOAhSlsid8quOesJpG+Lpmeh8KSbhgGIIdHPGbqch7WyIC9WNScTgP55PXO0DLA5hknIkzO8PNzquMG67il4Msm2J87nXKyJL7l3XP0mmthsBKu8tSsmrzWOmERSB0fvqpmLNNJaFaQYRLl4nqpU8owjRnB9OJC1N/a/OM1iy4L4EPXJzmWV8R4kQZ74KV4mKzdCid0rSZMzw5g94Kd9rVY3d4yYLYt4a3MeaZpxE6MvPtx8VfruTdRfUFGB7QFbB141+Q8Br0zQD8xfaMHQtYVZfpU0OWLKxiKcqBs4Cu4tnRLW/pMONMgkiMz+1RHrexv0y9pItOBX6tq6PU8lv9d7J3AAsmE/An+NKDNpNLsvVhV28yT7nb64P9xVj7e+i0+evNHqVyCjM8GpXkFxqVMw3caAcjFOHoUkiwxHj61T03jldvjY+LQXNdZGInWr8heyUXsaH+P4QAeVUPSzYcjhyx2MXmFN3nT8Ti3XA8OCbafgVuthrJVtUDNBC/ZW4I/pfMeoVIAYVOdsMacthzjzzwkU3BJykHwlYFnjik1Y1W722gb1GJVx18SPbo1QyTfvUx
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
