---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgALTmRzgfenZLl4h2g/3jY5kOW6c/eVpj2MpMEpoH7t+DDFpbtbXJcXxQVR/Tjf1hCOkMeAopn7PNR5y9BejwbMNeLCTHyfi5JanBm3uWVCYnQK+6w/Hkwy7l6m0F5/mPPZNELJUWQx7uVL7fqRZ9syhfjoehfILG7XanVpSYIIE1nTdZj9nKJ62Dj0u6mShTQtwBjDm48wDK5BEawj8SuePug0ILULj5htCR4Fv71/w9caxO25ZR51Irdw1WVDDKRW9fwp9YsBtpOc6Xac+/d2AnYbdm4DK+Sc+LIhKrk6asggdLst4jHVAIYJRSL1YsGArE8A580tw1AxIUykAOB3A+k1TD3M/OFFd2k/spQAnILAdZT9GdGtdPdx/mcmgg0OjFb/3SH+ygVsDvihjBxS/+jQJHa2Y5lugFK4hFUOjUjnbowxzzIG6egY3Uph2wfnygC7EkgoaCwcLiX0Xct7lRgA5zDfdLdm5ZmZbpVlX7WXXrRJyxV+Of476/CmsTSS+ivNSLZSRGYvIW6/D0j+HoS6vdMY5UjTSWhax/rPu9g548ksod8NNXRsy+gsDVCvatObbrlPYjpLGHwG+FFxmp2lEWKIpQZGqw8a00wTdReVbfUKALJVAKJQQkazieJRnrfjh7EDb5/tg0p1XK2PqrlWu5KHHt8icx/tawfVdRVOxjxRoNEYO7sjtyVz2PphHAFNqZ2Z7JqUY/Iw5xQ9wkq8gAvoUM0ZYrS0SwmF30oOxBszoT8WziwS9KOQhCfyzfbIOu2nmHRLEUmHhFGJ
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
