---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCKWhpNNr31Jb9szXbmhcq0sNbo0na/jVw5PA4p31ImVdg0ScSBG/gYbAJUSNAaLAxLYREZltr5ZtOagZg7IpnRFHdJbjYQP+hU1FxHrTeqOcV3Rak8R55igJk711SOx/NYBEmBm0ixJgV+LdfuwcE6kYdP4zSkJVK8HSyA2XyqaRxVuE4RUhMP9UWkwnHiahbMr1dVdM9G2XhlhjYcoXsOr5/ez6mHYyZie/VzaizDcsFcofPGy9mAdVtZMAPBTsBwFhA5e1k1KiwE0somd/MPy/Gv+PVZCzpIpzDYZlVuffOZNsCBZBbJ0tVDkbBlxIUYubuw6mCbQI5BJZOlDvVsVD8skAUTIr+s2MLLYJxx8s6q1YMdUj3p2it8ypWlcPH/iSSdsrW66p9e8BmaTGN6xkDKeAVoMMgbL/BWN4LqHfnlxwn10jU++gXhSLhQolpcFv3kTZDEExGaPo2e+Zbcrme9rYFk3PLRDgx2eOKLPnKSXPBJCL5uqcLQENizaaL2CXDYa4X90WyyVhEA0nJvdrmlW+abV6MsmKrnYhybFQdgQ29aiJNUx1ieVZkSslqtzkxRV/IrDKWtWlBK2+3e3u81C6AZ3rh0KFbSIz9ENB2SBdSFV+8Ke7H7UwvI8nWV908skAWFNigc0PX95/DksKfCvV05js5I5XgYhHDmYbfr+wmYSD6opkR4ByGQqFMhUBEEIXGcmg9GZtjjqLkaseDgWBKA2aXsRQT3tDjJK1O2r6F2JMjEQJjEhWKKr/ciK5v8RW0M+XUDZAbKCbfj
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
