global:
  clusterName: hcloud-test
  kubernetes:
    version: v1.32.0
  kubeaid:
    repo: git@github.com:Obmondo/KubeAid
  kubeaidConfig:
    repo: git@github.com:sbdtu5498/kubeaid-config.git
  additionalUsers: 
    []
provider:
  hetzner: true

hetzner:
  mode: hcloud

  sshKeyPair:
    name: kubeaid-hcloud-test
  hcloud: 
    zone: eu-central
    imageName: ubuntu-24.04
    hetznerNetwork:
      cidr: 10.0.0.0/16
      hcloudServersSubnetCIDR: 10.0.0.0/24

  controlPlane:
    regions: 
      - hel1

    

    
    hcloud: 
      machineType: cax11
      replicas: 1
      loadBalancer:
        enabled: true
        region: hel1

  nodeGroups: 
    hcloud:
      - name: default
        labels:
          node-role.kubernetes.io/default: ""
        taints: []
        cpu: 2
        memory: 4
        minSize: 1
        maxSize: 3
        machineType: cax11
        rootvolumesize: 40
    bareMetal: []
