apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBBs5ZenD7ror/AB3i/FjwsB3+HSAChD4viNGVOdS/D80SbGjWAv5bXN/Ml0FKIVDR+Z8huEgN2XmQpS4wq9W3+oZDkKYu6aSe9omE5RJpE8nMMUOgb0lTSBZwMNKcxBHmnGN45OKhOYUhte2p4P+gh2REYOfksHWhkZugRKz/XKjnSE6X9l1tT57Pq14TkeoO/Ni6dpcN4HMkBJcj0cPAiXS/xgrXk/H/NYWw/PEYy2LCVwr4JSRQ5086vkQRQ4KZJ4Q11bpJJ9Yfb+O2tSGQX4b8xZmRQYfCTw+tTz5aq151gher5bSdT7S4swLsMtZf/Dl+uYlq813w6+dD+Xb4ho1LtIM6sx12DVpAFzdGRgJesj66wE+0KGxeNkZzauohkrTAsjgK0XinwpJYSDQqEv/aEciHH4K2T3S2cwtljP3DvDgx7Q2DnH52UG7WIt6V8shXnP4vb6JP0IMlFm1mz05akgTs/0nfVKb1CTC4UmGja8XG2iIrUnjhL1cVK0rTxFpRzqq5+HmZnxn8bKYViUZU4OE1F7IdMhpzDmfPGjvxjjpA/fFzoM//UH8G4fUNVt/RHfnbhNBE9zbGqQk5S8EwCt5PyWgNsga8VksQd4R/6Wab52gqepEZemIxbVFXUr4n+7yKsqaaSevij6DFQdxMMlpmzeCskW1NrIempCBKozXWB4MX97vPwuYFyu/dwWhqJA7pdEfyLecKlkKDtqloKrnT3n7/FaLDtOr4cjgZ/UD3bTc4I/a0XCBS/T/vgotsrN3MKXtMmwePAKNpD
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

