---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBKke4evqt8WxYk9bavFceDczmRuA6jn5hjrXVB7E3I1Nmuhnoe/b4T0fZ9NhuFhI8Pg8I6JiHpZ/HOWdrS4HotmprxSe/ZYYwdlfkVuZJPZRTsYm4MTgGQM8yqUigk05gugKoVFs3OBlLIaPzUHgl6k+agCZi3fbU5Zo2rr6Fn86tn6VrBM2O4HaXRR+kcUMLiNQ2VryV5+xugJOsr4tJphW4l/0N7GWTLS/ToaiKkIQNvLMGWm4xJ4j1qFF/Z9Ug7YTPTfFYFXH/WPbnkghmji8lgi669pwAjklrmeQIr3De3NXkTcRPZiPoocZGwaKZOkXgALceDt/u+vpUpKNAXVnHY+kUJhcOFSQj/24OqFV0JPCk3xe7TvNHvLjzgTX2zLBcwTqk11rG/QCv0v/umoY4JSPQRiiN8X35gwK2cz0ZxNSoMTwfidRytfGiOQBNbzip9AxRagXBPL5uzxF9s4HknfPdl4EWzlLhwNI+uoblcPN46lONZsDjdgH5IaiD64zYUe2oBwvFyt0gnVSM1auHb6oEveqVl/bbid7/NWhJGFVvU5j14g9rLyMORWt2mWqzlfcbqepMkTsyk8oynRMQA6/Z3i7tXDUqknoWzZi49csSCKkCY9nC06kD+yYBOOn+5sBJlpedL5BruSSsWYeJfuI4H31l+J/C3dnSLyOtDflPoRcZu04id+pMf0poYJjRSGSYu2B7SqOvjTwcgaisvJOMq3JSQuECTiczwI2tJOHdjegweChJRvDbAWr7rbvzwULEsQn/Kx42Ho56i
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
