---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBIB57F48rK+KRGJAgF9WUvj5+qmisfzttg13XgQ2KHMR/uYdz8ACCQn6r0tpgibPtXCol8IQVnubq6QN8v5ZaLMFZ7vdSDgEn7vELkBLpUHlFsZEEWsjd/TRN4IrSI0yIy7/j0saTw/F4ZRzqR42Y6SustpnyCarrs8l52wEf8mw6Z7hywqZYC/YZQcMYHH3tzgu1yA9SQKLi6jKZ8qdb7nCCFuaeW6wnfpLpwRL8O096yS4wAyDB2V4HYXhkSxEYJ93YCJL4aRMswmdmvqSzDwgRjINMOHsho4nBTcqwXa/NlDjKekDnPzrESKUJZ+BrpawD7SZOjtn1Zs/mmtUXuK8dciXdGX9wuDQDbms757iuV+Z5SLL3+MoZPPcCUsaKNFmInCs2D8QkWEEHTRjyZIhYGUJLBGqNXZoXkTasn/TNvqBDrXZ3nZ4suGky2SOVL6lgWkJctrXwcaSXtI49/772mZzrCULxIv8oL3y3uDP+lOmjhDn+RMFrHTxzXOG9HD5aDokr+9WFsl6dqKxc+zfPA6E4iwqb0jT6/FqRmeZmuo8LMDREGtxGNX/Pdl2PYe3oc+crTsu4Ktxl0IsvG+wY3d3uBZaGkwzOcp04OHHx6IcQY5T7wSfFUFktMegrJrC1+cTBY0vVAnbUyvAPBdQiU6DR9dCI6hAOFhd4ni61e4JBqATFQCm8bLFGzTRSA2mxogVNy39CYaRMJ+7jGOk3CyQ1i9jKClCJLX49IE1EmrnED8c5Xw4JxtorsUHEFyo7i8+VpWnwogSZ7l1LW
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
