---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAn7sPZwzXbGAimaUEUeRH24OIKRwazkqUvN/kV7/ldVoMIEwpc1DBg0hUT4xcrVu+5aJuQQBoCz4kgRz5qyaZt02vkxHKxnV/mJuEkIsto+RgCDoDwfBpNVl691wBcIDrbL+kTK3Fl4+uy7vGfArpq7Wx0uDSw4WZhr9DsTA10deCPb48hmtSVnVo9ZkKOYtEGk0FLdH2ZjoWex4uxqevzJiAhPM4P0geJlh0fv+s3xehFUEtivetTozEdq0oKR0bLkdsUgnvpWP3cHoKz2TXwxj5Ew4Iy1LZTzHoyZe6i5atA2drXobUlbKjLivyQ7NjXEwRutj1wNCUW6q7XpJdD4tT35uGT3McDzbQvra04bG4j1XHD7Of7BKksTijahG1RA6oL3cQHJiQuYf8m8jJfP2fy64H4EJ1KmU6zJdC1e7R7NjKBnbZ/iandYlOlnbIhmWP36q2Q4tpwdtmlTpwUD5jyK5IE3+JCIrMHq2/3eWeU5IrbQnQ0Jyl9ysT2jYFFGVmQjAl9pHo2k3Otl+2TCcLC/wU+xzS6xal2BxeuDDBBZn0DlGLnz4NzWlPgoE4K3n87h8DnNn04DVch7Q9Hb298ml/QikA2EMALZb6DQSmr0FfAtiw2FR+Hhk9CRBxf9pKt8yoL1mVqydty+0Z+fOrjPTrDjiN7RJ/BC0UUCkCCspoFinlvctEH1gGTG+gyflX5K0S/xM7QT7ycD6BcbJ0kS6jLn78NQ+iHd+WO3Gj6t/PipSVKMi4rPaFYZ2E9Eb0bcRBkC/ei+3Jx/QD5
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
