---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCVuhqnhfRcvg1+gq8CF0ZbG3HHE1hhIkywRPr9ZDsOsxkzroMPOB9qSHpZp+8pI+6ZslyEgLKsyaJckSiIXFPAg8fvGo/ZTxiieewJjY0lm6mqnkvt3JtKQTyMDmiXKIcEMVbVoxgIUlW2TrWFm9r/r1r2Jrzg/+N8CUJ4es5CTXYUsv+/BAJDAUl7ODWM6TXIFgcVmDlhn+ToBwYvohbjytul9lTHLINSc/U3aDU9xcQRtQY+Sqj9BbOb4UgQOZJBU+/1hWT+BDXPR0hz3SW3J3h3FtofqJBCPgWpYqaWmtOBac+CAV2N460CJbvGV8tgpGJN9M+dTDHGbSBx2Uyf7Ks53zZqxSIpm5UaYAncMckSSomAADM6rSA9BZXvzeCpj7lEh76a/Xrv2wb4UCENiTFIXi0YTkbj1BIJ/sjv+B5vybAwdAHn6WRtTriMBdHRIkFNTzExJ79n3lvyrPkRScs+QsxgpQ+XAj+aRq9YIO0FviWre15MIVl5sEI0HlX4RGPeodlDzMQtVjg4Vx9EDos/9Ot1Nj0STwOmvio325+76ckEifAVhqu1NEGcBSbzvmoFAS2rlwZ1x2kJfAHIsU2mXEP1HP8p7r+mNvhbXAm+vR5Lt3kWf/47JxYoOOV5WxNil3YDkD1icHkvc8JmdGpeFDkmk/FEz+wxB45KIyO3qpGWIeTra+ZknuaQvHaiyD0+jbrO5jt6UhluSTSoK6i42xjOE4HeDn1XdChMrI05BvbHeMZ1uj93hxXgm5yCTFL0Kj2qgJ963613Kdek
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
