---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCTrc3pdgljO/P4Dc2N2sU2IIMQsIejJhonELKDRYNIgTQ4HOD3wkOsPBY0eKmzjHXs/b9ZhhjCXE3WJiFPBtk+6qs1LVybQmwxtkezNV4hJniibvV0NV7QXLqXzpdwLJArbBqriaCDnlBG3vbG5ys8L9GpXHFx9jWMv79Sm6/cAtfiisVsxqSSCojohTizHH1NG1RBsDD3FMd1BUTVyFWr1TN+/pP3txIhM3TUkYAUIcN0R9tXMUHC1C4PmvFxWOscfGHMCO/5SHFvVlVpoWt+VH+YzQdYitr1lfm6yAq+jYL+cdt792UwZLXJyhaf37SK7clez1IbUoL8ApJBOyjFyuOvoaYzUl2DVmtp+FRVj7SRFSjmvSjirQIvV8dswb72KtzvjVrRdM/ytnX2Z7zSXKvkfPJFE7YwKF+U/Apy/rfemtipxROGn3a+wLL9jYyhL9bd2h16i9Cy0rpqNjeubacgXmHhezmLCiajLtpB/kKRGcM8C7q6daNX6pP4U7Xao1b1Yl9okuPbhE+e08Q71hCwbQJqTD4n1dgmf3enYjL+kqspFF2VGoZsf+pClXJdwwHhtgeKkXsbHsa//yMh6ESw+hptiyh/SCi0qKMOoe/mHtRBnJ6NTIOghjwz2BEj2OZm/S5tL+W8FDwq2/VF92OVUDSnIc4ECZif+UZ4k6T0rh0hrPZQ13yW7Os8/SbssccGcY+6CaA294LmfXzUUKlarrohbQExMOiZSP/NF45zzL5JfMjboLE7EYZun85UOat6p3DW+maaitD1vfoi
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
