---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBHrVQ4z2ayCWNacTAnNw7eUNGym2F3Y27pcFaH+G13gq33Hpn7OstZHHB4r+Ly5gB3noVqtVbETX45ByGE5Scd7mpX2xviCx70d5VXXiD6okldJNCbsaS0T5LGam/Sy0Lnewwqr/eHdj8ut/SnNX+kiBjTCVa4yd/4unBbq2BhNDntQLK4ViyTMY+q69Qp9z75pARLFXHkfkT7tNWiIETkbliip0O92O+/3knXT3SMtlribTVXjWlrmN4976pgaVgIaDgdI647zIp1AoaQeIiugX3wHYJXjQeOfbONAiRVUIbCE49cOwyDr5jh5lb6YamiUHZYiVWvqaf4IE8u8vfbE0cUtxfMpTSo0BP3U3SLvu2zmmiudcUrRM6WOUlO4xdd88A2iM/ETZMCpe2lTA87spIDSuwSbeuV8izUNFLJfF6O6x9eY8iu3tnhdJkzTsba7fdH4gnB4W8kYb28NmbnxyQV7IMy8mwzwNUquRR/12goPduVUr7eKO3avcnUdBj661LDLpL3xKf97duDXPjc2sahiDlLa33IXdG2TRlTjjRES4ZSil5Bv8SAaTPfc0AydCpWA8aMEs0LrdHImnGF/1JcAXpN6dUqSULybm/gPVvU8bE81AIFtX99ZZ441hxE6+wnxPsaWxOCTc3e9jmJs12L2UBo6p9T6gGqSvPOowHAYu5ByXb42vgmFk4Qb9QbKtsznKnm/JZNXpEiK9p3b1Ppuym93j0P150pr7Jap1mJuE83hj2TSizaghKe0eGHxB03lWUaTVHFyv1kws+d
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
