---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgDSrdJT0jYxi4ZPK2wJ/6X39OyoaNh9cXztwIBigMrlM3XSbkL47qjulQjLJ2V/QWQbSSWc8lalc1bO4EPCiM2Y3Mtr17X3QvZaSJrRcewagEMFGPSzJVCK/EomjUlC/lpxsvvq+MshvywHVFV/kwQvggaFTpuoUCHYAqtR0G+mBmz2C0ivd3HIcHk+rW+MAWZv8j8c03iM2raT0QUgj01utc0JXqVmaTVpAZOi/S+7DQcMOtHuaSjH7KgZocfzG3DwuTCco/Ae92ZYtxAk6NafPvW/qw9at8ffO7bPZNRRn6wa/CU/9ZEhJps3VfZzBo4gskTnTCuaaFLJgivc+JqX5F7w8t+Fzzp/PRnnfOgKNLlZiUsE+JWMWBj8wAAHBNdpRrcLenejCy1qa4cr045oF7zRc1AnIQYb9WmMLatu+mrlOQO8wjMBGi44WdJTdhkBjnjSnLx8LYFQeXuxiUZrnkueW6eAh00VOFTi+0MLecrHlx3hOD2iZfgApJ9pES92Xsyxg2VwlnENyfH2ndhFyG5eNbXz5tBcTT2BPJmRzcnLZfc6c8t5aLhW3XliRSDz7ku9Iisj2XNt/MZApLSDFngGuIqBIqSVEQi5+sP2T/KfRQTpv54JdLHye7QU1YaNSLrMBkhESUMlHTZUYc8P1RZ/q2xr0pOOXcONF2OF/fCRmNpm1oGBx1ahxP3A6fAR87Hh6nkr01TC781SL2fgUOsgbSDIM6owHREVuWhTpw6+fM7AuD57EZlhXNeRUjhQeU1Q6rffuB3s7QhkiE5g
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
