---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAgt7CBuNO3kSujEX3DWI0wjP70gTX05eIHUw92cHKdtTK82R4KWrt3p3OBupqhBgd09nZf3srXuvjMYIIB/xT5MAtF1R6gNFy9l9zFal9k4CvqShYweZiQqDrVYoQZnq6ihtMzSW8fcCq2vQVIpsASUSMvPjWEIxkpBh+I60aNYhVSoug1S91rSuEQtV9PC4aCjMy0DjGg+BkMphBYUMhMeQEJO1aRIt4W4b8XipvER1hK5OJT9EpsBNiJnqpxm0LDJGzFFXkk/iloZs5GM5RiEov5xpf36qIB/+xTkIzTvRaQqYQUXg9xIPSI3lEr3qlXomGmbgkId3z5quiAgvSEB4Spn53uZD8AD/j5rZohCORGpXjIKCo4s6uJHi23Jfqctbw1b5csAOEe4BgZifTsxCJt/VvURnm8KTFjF0AE8JzR219jrigiiqo0jII75r2jwoZ4vkpImUtEgL2pokXYDFBdJKG1C7+uZK3syo2FfjHWYMpxu+HMPHZ9V9YrSMPsqxJrlXyhSCWLCVVq8qqjibk/xuOwnJCbqBNQITwiiYHVzm53kMhlKDb4qQZEhgbagkoyKxVSKfIKV+s1tFCRFSj2CvQ5qGpW2+ykrc4TWbbFCtRkPUc1u4luv9R4ttC9ElOd/HrqomMUZzrR6axPNaIyUJV/0TT+XEjg4aU8OaAhILPt0278H0Kelh0EVC1cxIIUSUMADlHYcqruEcoo38Wn5y8KT9RQ6ACiO7CSa8kRmf7Ertr7j+i+XQkBEtuRDWCmRtnjbRlTZV/kkuFV
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
