---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgDIZ+S1fPzFU9nNsYPN+TQn/VWp/4rOJNvwMTyE0WXMswdZF1isDz26kBB8cyix1OjSvjHvvEe2OumMGM3Nn1/kqnLHQvB0+rSdmoKHhCwsBoTDHip1rtbLg14i14Q70kWPXrAoR1AvjXHfqru/WY3NlWPqqYMDgh0RDLN5ElpyqS5TVpfmYTc4HTw+LFiSPzpzJZ50dQMRorSxyOzeOq4uQme7lH7DH+yH9kboYe0ktz9Xue7w8WL8iJMSKfAqtCVZbt9a02kt2P8vV6enDehiwcwz9FVEqylCHywjhDcnR+6p8H43u/VikZt+lpCxlfkMA7I1SeLG10ntuWDOo2Gd7/XWoa9f9JoYhj06rQroJQg30r9+BJyC3pRD/wkoN8RXV6HyfTodcxsxbkjYjHZyvkKfucQRYIhUCOJDmcMmthfXeCOea5kplGCVgEhUjJ8npQx/MwQ3hnijYno96swKg9Ss/KTkSFkq+6/RE1/nwBDnPYIrUR1AItCrZKJFz8VjgGO2YgKd6UuQQuUkWMIT9dfTtLKiVlLtHVADPf5kNZvOjGbSdrc0wCgJ+ll5Qvy+ymEIFtG3u7ne1l1VSDMjDL5PQN9FiiwQGLKgsYkmxAz3QJdyPDvTizi2VoETZfwJJq4+M5Jz4PvXUGhGrTPqJBRnm00uS4ZZbEJElqQa4DRc7okl7LqIy9Zqwyq7FrCz2rlaz6/OoF7fzkykuA8i0/715SkOmTUqi8pSaA1SFxyqVojNWZWK7Znnbq9lagGWEImn973pWpfzUDS8SKEy
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
