---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCSR7ERcIURXnbVdkvpKc/sZ0sSFShcD4ojLi5fzXJi1XxhS2gW97+sIRTdjjTRh7koxkOI9mtCgW79lahJFSNvHHN+RZKkwk8rQsXvKzkCa1mctXyrY+tIbiyixDnIQkCzjh0/5eoY6grZc+D94XEK94iR+NlTPw59gJZsmZlekhikFH6/ONzXwRIJgOzNLARwGEJ29gESbVS5hdsatF+zmwxMbophZN16IEuKVO6pEh0R+HsjP/2kHtSO0/DV9xm5ppjT/kW1NapepKLCwhBUVwaJHTNNVsk79KDS2Nb6adS1HZtg3PokzFq67u2qHUeC4epUqSV3ukBzMcjnXxyCYE0SKDPPpJm6xwETTpLGzmQtQ/ROZl7iM3BCpB5h9IpVAulGdV6QWjDzIMGJI7m1JHFdLrIC0rr/W0Msu9QQBawdaPT2U/N56/Gt+osKT6S/ah/DLcEnCI94UbZSZffrN5yRP6IuS83esQfH7mniq8YYgQEIGYin8rpmrZZa0KcAll/aNsycp0VYI3to0FHQyS9zHuIoFoqNFIkmddnA8ia5D47vAsWp4fT8GLMnG8wzXYFdWJPZCGD5quG6u0FbX6Cm2dseyrEFNZHy6ITstoBZC2d8VNae3r/Z9y1Mo8F2VnL3UTXFfOAGe5NvGkLB+oS5Q6AeZi7IWDQ8wLIBeCVoqaj/avEgJ2ThsKxoiCIJWJ+CIzhq7eXSWxry2Gj+5Tw+RtxJlrq3FyjchCeMuOUSIjgg6qntoIT/hwkeWONsh2wO1G+AsFDh+w3EBdRw
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
