---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgA3a6Ea1LXRwBtqCZtoM7r9Mcoge4gDZWNtYKveUXlfL53dhtEJRNL0CDF2/ya2/f3teLEUygPd2QWmLnCDXJ2BYk9H+4X0AWr3zVCxooWdqMYzDz1feCOUBSBtZOQb3L+SD6ay8AP2YS+ByCyzrSIqPZDkJ5XK6Gv9HHFzAaQCvpTdjwPz64N6AK2+nngUfbQr0Sbfeztsz7xB+ipKIDBeY6dHjwIbufeupKkQNgG+MjoHSdFrhIcS7QfYUEERO9jXeB5GxY8uNM7apxbf5w3BxsOW1HdrTuIT8RY9AaH7i7C7Jfa7r2wKX24yselDoNFDJCOaw8oWEDtzWCYfvBfUhRwd0O0if/DFVGHzjjtK7Y2j5PVcd6yzn7Oze1KY07DM13og3m9N9yQJZ5FgvmSMR7k5lzhDybU/kOme/w1p92dY7MFMN3Xbb9EWUhSC8D8uvIt81I99/1qXbPrZQSpEdkrKjmUnmuww5Gb0P024EC8WzGy9L9AQlpoouQVmNnrE90w10TFqM4X0XOiNpzYw+vE+2JNDlryiu0dL1NcKBbuQKoqb0uGsCBTfUPCtxTmdkbH6zR6I6GjyrRcXm2hTmnuhYoRd+MeRcae3G3cigyjybW/igxOKjwdTqXeVg888M85SwLikN8tlD7t2T6mDQBIE5uZFFjffCcDwzGhqbGTfdxeqIqTvxoLlCnOaaHCAciC6cZa3Ljw9H9hSzcmT45t7jVOWxXNZ0wkXzRQvekJxE9fGexib+F/gQC4Zf8hMIQoAZ08Kw5IyiCvJosOV
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
