---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAmPo8czCRot9ltKJq0zDMFXbYQci1l2idWohr/WqYq49wmDbt6Chpsml3/L0pK0fE3w6IvWUoYlZ4i5BQao0yrC4CsnO8dCaclOjBrgU9oPu60da/R8c0OScCbtwfbcuCZT7dJrMqTDTBxtFf5pxBv5/aQvRCpTU9fCkAEu8ZfHomutI3G9RMS5JMoLHzcBMmTd3CcdXwoY/N9gg5WUqGtjumEEtIf+ywwcgsX778tR5TMjEpI7qoJbNNiICWjdRqqc7O9LoyLlipwcR9GxOIkKt/F1ixaY6wGFFcGqyC/h/PR+yJLWN3teZ/6gQpVWqQlRU2Jn9HN+UMmHD2L5uFt7soVh1lAXp4TFTVTv/KYZodbcmHSVmuOrGY4bppaWs1aEHzz6ZZWkae534RIERrfAQkJzYf7ITvXztVOX2t4FRdDCRmtZbHaRbH/nBoGkdxi+a7hZQDbs1mt8ET+IElqk2W2knipjeyJelQE5d3jWL2j0SHqcTgYoIUf4bIh1pLhM2pJ01HI9lVsfPDKo+OKxFvKPzkstWW4ez5+7irnYPjIF5QWOTrYNNyol8sXzFstwcWUww6e62ypxNzGA7zZLfD41c3M7UMCsxg7pBvzouNf1TPGBa+s7EmBJZ9ff2dRHYDHQlB1pWIB8qMnJKErIk+fB67bNc6Hc+cTBSBt8hc7MRA+TXP33MO+FOeEA2QuGukQD0Oo+ayukvBRegeWrGpEXYJ/gFVr52TUjk2ZVtwtR0mYwufa3W1BTWFdBrUSVn6sOSdbqGIIS9o5WP7Z
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
