---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgACgD/FpIY918iFCwL5KZUtYbR99SIngBTbpwHdod3aj9rjJLsc0IXD93dvnXHffcdskcEtOolfH1zXnMvkn1T/z70oqZWZQOfRv0WU7GLeitYmoVz5MxAt24fYWlHmfargdJozb0Og27havkPCJFOFOtpdp+eRn5dI1as5WAsb1IeFyxrZDFdmhW3xuPUxEKnzKrMlbfAMP4KYVw775hvBj2ynsQbJFQDZTW+91Go4mQpB3Y3GE1RusP7hwUohPMurSyehdEEChfqypjHhYsqiWh57P8d3yivtJjeO1IM1VYr2yX4ySU/SHtsZrNgtjwkpqHRBLPUCUVj5GnOaOM71wFJFEc2Xb3E6dkvBfHAhuvLj+9mC4d0atvpJGazJZAgs1P1pBTWnx/mAamhbA3qY8PAGPlf+qND1+1g7PzLdgoso1DdSIwuMT5gibw47Bw8IWueo1zybtr5lA80WWU6QpV1fZVur6AhpWvxGemly0hHv10joS5lS/cVIq77kFY4IZjcBWFcKWWBvJo6spN2WAOvSl4b8DXXkdSkz7wY9iTCnsEubi2DSmXprLjaNXljpBYwf1i0ibq5GigHnjEzhP9/Ewo4kn1yUnBlZQCujpkU3gDY9sYOQ+EwdngO+3weQT6pHVcHWRRM1R+N8AIH5iluQgfzacvcJbW9MWZBHU6KAW5FIyQ3qh8QDL2qkl0on48zM0iahTtcMcGxO6++SU3DZb5ZI0IbbKwov99ksvju6BYjwLgHFDClIBmaUu7FDqWcjLhQRtJjHv8OovdTe
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
