---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAkMT8KBmfNxPyeEHount1i5r6Rns1rIqlJMY5P7FD6XE7rKbP9wkV1nEOnSd7UrZZZNWr+6uf3kUDHPOGvDSKpjb7gHVnfy5TXwCvgA8oahWazfC0LCoisPD1cwt5rv7MOkpckgfo3JmNcg/H2qPkAZMsoSADNeyY54CqKhU2vyegFRsyt73YchHosqJreTOl+TYqlcfsHN0GayxFToQRN8TUeNsxQUPGTM9c5AKWihiMVLRSHqQcXbhIkDn8FSuK7SZHqVH1F3uyRlbDdtRWzVzPbfklFIR5XpUO9+2FL+hc5S22rZhgUn0r3/NpWfDW38TVZs+nR8Kbng/0RtFKKm27tvRW0DZAYTa9nsvHau/guUKG1NXlY7LhWQMTKhRzVhBok9r9mhQRFqLOO6dpp3lTqcaxUuoIQARclhw0AfqCkLQh5xei32p+AIbQcOdps14C5mvYnztefXC+7ZsHGNbpd779qQxuItdixyoRX0AvLnisVcIqeMymBHUc5dpy3W1LGXQk7AES2lcuRsoRKVBoCgZ33z+19MsV+9duzH8dHT+baxzSXPEaxHRTv8S0PlTaaEWGHlpBzqe1jLdUjwDsVA1s1CShiLNJ8en+mqR3z/fDYz04pO2OlBNmUYIz1OQ711vVswZzin+Tn0mKxmbtsC0yg1/74Ih4qU6HB01lfSmQvmcirbMBsrqP2FxqcjgynSd/vQDROd7QVLcGWCANxN/I/qYHJjdwu5lEsnZdSqSiiyx9jssrdF5g5Ot1iOJmb9dgvxZE46lPJa8WP
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
