---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCDXBoSCSYAYBSHaZIJ1WOClCR4RcArO31Iwgt/5Cs6Qwks2Efth1Wi6vazmMtXapsZGkTNZuSOMtrD4viAx/V8vhFdFfa8RZlNBn9xBFjiWcryHKsXzvHpe3S4y0TfNT5Sf2kTmi2JqJVDbiDyhtXq2F2WtnebaL0QzgJ5QPinyK1Fy4Hfcbxwe7w/bB239CdrHgb4zi3PRm3PrNaCcAVEJT4hsbMFnfIU7jNmzIwFnEQDJSD7izzb2c96P1XOJ5+aXg2dXqaPEVhWsZgNrWXszx6dB3Dx6wGig+ntswkPnfaUbOVBEFQtoIHYB86xQB9iz3ivZWD4Bn52eAu/f8htpQoozxAoEBGMMCV0wxFYPhl3QevFgjwBaU2Bn7XoMPEQlhEPrLq6SAW+Wv+zWdcAX/ReDUT2Y9bZt2X+BNSHz3pze043r+7hfGd+/5tvaQrZTEmIqe0w4MUymbB2tSr3Oor04qMARyhGx1yLyr4mgUbFqhY7OzxExkIOoq8Pafmk8/3TBcjC4qs7MwoYxRitXpiKgTbon6pkq4UAmEvEjzHfQ48KRX6thwXFO4mKnUPl4jNMcR74hZ/xvdPfCwF7QtgO4h/IVPEdbRNOm7ZKaudPQTQulEMgqR0AUwHX3iPrMUdUemhLBch/41DygkIk2TSJGWwSpa39fObbf2Rrc0siGf2H8Vta0BTKCRtC00lmGlUK3/0W/qY1K0sd5zXxZqsnjBgyPO/tqA8Ez4+VsWQOEi0n4A6NX32UAfg78kKo7Vaz1pP2BlkhgrrA829f
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
