apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgA3t2iW/kK+0gjG1l/85CxuaklRzgqRHbm8Q8EbXxkk6KBoF81dAGw+V6QoBqRfmEh7QqrzXU0C2cvonhpaa4fe0HEkgcZu5VTAk/vH1+GG7vaK8tYfGVfdDa2qRMyiEUVIkO3LViZwAZeG+g1qbjZwdR9xxqYc3C5KmBxzrxZcJW908gGg07MTnn9x2HXtzb0bdbmIg/4Cfl5a14D9+fNHkIXO3bUtn44PaGGUSERMEUQhOH9J4KBpFFmxSCfHJbNOzOYq889O8KJzXeg3Se4z7NyFUZ5xQS40Mdzanr7G/bbuhteM5Q2O1Jt4/vI1YnfJnV2NdX/HFjJwCm5wEx94fomSm1+AmDHY4rp0JXoqT/vzIO+wdbb7XxxHWprZqfHytJeiM8YqOlzDts1BOtTtMOKvTtzF4y/AZycKgeLmw/vkzZ39JFMorICkIbsvqR4xkxGMA5eNceKzlrI7MYYivBDvJmqjRW0rEqhHRfLmKH/tP5yARxbntll1/ysNAtIIn8qr71kl0cdHFK6k04IR6fLRkWO/4/ZUl0p5YxzOIJiPU8glWSVtKiC0GzIHYDUXdbFGssbfDtnowfHUO/UmYXIM/ALFP3yLsc5po28zVnpNJl0VsOAKOWWSQBKX+jRi9Ex4ZNC5t3v5+5X9FcGGRTD3AuJC/cLcPSkMinlXxdmpgtzzOzaEz/EYz35yVT0YSzEdvlhqlUe09oQMdktUTpUEUFjsfSVgH6on7MX4qwUZEkFmu0PgQy0JAyBhr6h2bVCDDzuMKq5WXClLUw/k
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

