apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAz4qYGmHtd1YrXvjUXCstcrcFF/UW1GE1Ip97qNi/G8XeljJ1BGf7kaP5czJrTn9V6Cd/WSxPSE1Y0CWEEdnOeqsNvjdYaNK2Y5mRcQAritl8PiD3fhe8jcKFyabvwH7FZlzqFN8Hb2RNpgrxKXWobeZe1GDIKGys7ko7v5DqVBtdRar5U8oO/8l+1YH7afUXjM10/XG9pkWtQnea1e10VmAjZjLvRwk6jqJUHxHsX2j2/RbjY8ahgcfApd/Lhg73ErbThEywJS5GxxgVa3n7cIk7QPfQbVPJba2kBJzHmkYiBLWa1tlrn3hgD50ekYasXve0sYSc7f+3w5qxQTRiwMMYWCHT2kM5cTJ0K8RJ5QaU+6XiMSTTrjIwCPxnm2WOAHXknjAYAwj7WMhgmXT4tpQs+Zrz2/GkAgjpWue99V2bIiiAEy9m+5slFALhEeSNnDr6dHADfKce4WL4jsFXUozd4EpPM7DMnLkHTODh88o/QsStyCz28sdD8uu/ESDHT+BB2L9oCcTxi2E/fYGDjyME8EO55GgGCrFHhDi1rj6pFDGmuQXcEQkqyQ9Ll/nHDDX6kwZkIWtzOYOyuoEpQW2LzXcRT8e0kbxvnB5w6HaYc8g63gxf16kn8pNEhwPjNshd5EzjnE6bvX56izu1FXnrQeNYXib7O9jcHEe6x/BBN58I6lNPhvxpwrOzrwgeUrIxbQhXUyU/T/x8Ytferp/3bbCdSEMFQeVgloCwOhBBddY0g8Gs5fI99+gfiHW9btpp0kMcMQ4LDGopjZx7J
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system

