---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAJJClzIfy8qnrlCZyLZDGgk78ISjkrrIGJRAYKD0Kto1Td7ZbfmcSK8k23m04eDKG8PhaaI0jV2w/SdMPo015VJcCMfWUCeLZnYYKGDH08KbDZHm73OOdhChotFKigelUCLIWURhNL2BoMRVp1kSBytR8/MTVSuSZfraMyeDtDzAc8utynKJVGUqePRJUOlKXkgaP4vQFstoGHJ3HbEASeYJbC+/SVPBP82x4gAOCwZpdbZnstuXpcE+UtjTqGvuMtO2L8iM/Elx6Celm3vtQaWQ+YYcwUB+bN7qw5O51MdmgwtiHFXemQXB3eMAZVKRNyKDsjKVGO4Nm122Jj5Q7WO4ihRx8VIGJjvCyeVqhW+wh22skl7jLob99uEXB+nnvhcuRCJoNr7XKrNFUNm8+n+F625c83ssUSSW+0SQ5O6C1E8fDBr41BZDMvxd7ioVF6HAgc+3q8NWN6NxV5UxUvzHJIL7NU3zYRspBMfM7Dh2msKUrUsTcPVVP0RbE0Kec8o9lERpBVlm+l/2IDhnLbnJFwaQr2zLkCTWTgh9aJMmEfPW8XZKA5zAnlNGTIuwuPzmSzvOk9w93ABtoMV1d7y+22mV9w3cdYzXg9s6bSZq3iGk6zpP6SQKLwSw0F74TY9WlAa1cdXsFd4RTYrFmtaXMdz/dC40uCw3YI8Jd7a8vyxTZxgxeu/qNOmyBGQrwpptempijTaGciUk+Z6L+NCeLk3EvGi3E7WJix288zUiZU5jUUsMgbPAf1rq0NFBis3HicMUofM70/jK13y8Bv
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
