---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBOmBlH5ppV5/JAYl/Rjz5qN8OQmjo72lXQiv7iVUmcm2YuGxaoYA2ttb2Z0N3F6vtaOs2KjWiuN7M4VDmipSVGzf1v6O8VfSnf6ctm+YPQEJAV61XeZvDbQr1KaJDTf85VCx7u4q68ei1BULnVLC8DRFLzQUrYijeUfd88uBgco2oNgHxuzBowf32u0RHyXxtnFFWvDBlzGhJHJ4niYTLO/hHP9wGpqnHSSCV6LqBAUaZGX4uHb+Unky3nNerL27E7XnTAd9MXbreEHTp24+aj9oqW6/vHBJdfT5fSPMsQzXThoiDVeIjBDddg98CqmsbuCzO+R36hJYJSIG2mX+wIGqPBK1BTjMF9LKgM8gqssetslGJr/Kd8LouT4DcOLwNJIR8i1aDQW5Hvx9wxjzfJ4DpDLgUXmUe8lPwzkAXO26uGldmTAAsfpGuovXGRgQCigototAsvaSpLDTVcioU0IxmyvzycRfq0KSf04v9m4NTOqRn8aMhk2j0KsSZL9i531LselcjglV7u6ErN7LT+vhtcVunVkVN4P3MpAymLjtKfsD/M1RHpwRhLKlZvMzN+xzkyTNPu95vnA7kX4FbiT27Mnqm9COojxgjcu4ZZmrAmsoglN0KuXspZs9NFzcyhjtNjD6IDEqaSLmDE1cfHeFbjuun666rQUvsiIPuHC1Vqn9bQlXjmguxzxjVh73BMMxaSlQbjFHfzNhm7MINOI8hA6XXMriNmqBf2oukjIkyyz6oiGrgVkf8nmWNxMnO9rMXPglKU2Dg2ytENCCFj
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
