---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBb6Z9O/J0YjliqypPAzPqRWmmnNjWUXsr2Kxqz/UqlTlOe22hCYpNl9wGisu26x8+cnjAVN+QVn06+HrWxee4QbArCtA/42CmI1fwabH7xW3Slodf27POIbqCnLeU7g+JtVIO+lzL9fswTmZrhRvsesecNJqiIFliQ1PJlHYa11BkFQls0Oi8YSMI4T4qaPDNzwlMwh/yBPvQxXJBhlefnyisR2hA44eT6yXeuKAlN9taQiqqP10V3e0NaxjS+XSsg8fa4v/Pwzyk2WBMeP+O3xf7HRVcfV50n03RRubb+VFyEaUJpQQoSUgbIgWEIEL4iSIeSJW8oK/PFPWIzc6e2i6evsTICaKNI3P1cc1Krn+gHXUvMky9F8HZrgAhmb1hNOqRrCxIibeJBdOC/lpOARio+ke9m6Ri+TOi5Aqz7wnfIKJWYfsbZvzaI9Lg06VVir10/jzosWfTbfqe66qt6urJcr9k3hsxJ8cUQ/7tqEPOAQTYyWRpk3WRqOhu5xHStvVBcLLl6h6Uf9DG5ToaYLyNzV6dhsg7BwBPw8mJFnsCKgnGeGwkUgQ6zkaoIdNlWxP/Ye4yWqNGBfgsu2Qt3Zi8y6Hfvic1TdYQUn+eO9KHGYiwAdyRumXIRda7U+qW4De2SZUDA/rWjRlrsNktDhvBu7adeGuAk8Ta2/JcLkCm36zjNkoLgTED8BbuHk9Ztei48z78COsvUqBN2mkiifa2DFCcFJPIwXvUcfrXU4nmKrESzJvhwAQb5MdT8ZyfEes/JpBO8uqOfYtEe5PtP
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
