---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAOwEATX5ce8vNo/cbqi8bjPLerzjEKxHyNED6GczannFip2rrYxEs2YoWqZ96VhPEyit/qzqNbdxG4tPzrAjrHa/fWLmi+Pr45z/fln8+wOqAx9zrVn1QG/9zjQ4aHjgMLW7stPrx++3hNOtnWh05BK5UzKMonCXg5Tk1xqsdtvGhCyZ1uxY7iAtpH51XaOZuh1v+wx0Ooa3qKprbNl2Hsib3TYhxzUIKivydEIUr6VryqOKbLoImT7qXxfsIfyZIoe5dyzuFExGUOnnnzaxVxOkReUTbnVUgb1lOgSya4NVYzPLF2kl9zu/+pe0UhmrQXisLHCDge3muAOmJrphjp8t2gQLjwcdXIinx+n/zXfPgm+JCNXaIosC4CyKt85b1Kp5zYeMzJ/Ii7NSPJM0NJlTySZz03H579z33ivipsB/QUe6Jmsugx/oEPlipGBpjftWkE4e0d3RwcXv/BouS47DVrWx4jH3lmXonawVlVydnunyVz7GWlKDzGhw6HQ2V76NHTT0Zzb8t6fFRpJ9xg3DmIh55YH8X4nTXGviRLrvDnFQjp80wzAfF+B/v6xUD7bw22/b2SP+DTR943r4sd0PjItI+BZcD0eiVafCeROZvCpFnkoHXa94fNCKUpm9REjXU08tUY1veV5T0k7J1UVfzkkuw0avJU98tixSmmgEzycc+5on6bmjMJW4Yq6YAeUnA0sUoqa5QX4QiC3cWnF9RrsTqXS2KYutHKECPMLzzD5KMKT568l80e4WMNF/YVATpbyXDrbbqVe8TNCz3Y
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
