netbird:
  management:
    ingress:
      enabled: true
      className: cilium
      hosts:
        - host: vpn.obmondo.com
          paths:
            - path: /api
              pathType: Prefix
      tls:
        - secretName: vpn-obmondo-com-tls
          hosts:
            - vpn.obmondo.com
    ingressGrpc:
      enabled: true
      className: cilium
      hosts:
        - host: vpn.obmondo.com
          paths:
            - path: /management
              pathType: Prefix
      tls:
        - secretName: vpn-obmondo-com-tls
          hosts:
            - vpn.obmondo.com

  signal:
    ingress:
      enabled: true
      className: cilium
      hosts:
        - host: vpn.obmondo.com
          paths:
            - path: /signalexchange
              pathType: Prefix
      tls:
        - secretName: vpn-obmondo-com-tls
          hosts:
            - vpn.obmondo.com

  relay:
    ingress:
      enabled: true
      className: cilium
      hosts:
        - host: vpn.obmondo.com
          paths:
            - path: /relay
              pathType: Prefix
      tls:
        - secretName: vpn-obmondo-com-tls
          hosts:
            - vpn.obmondo.com

  dashboard:
    enabled: true
    ingress:
      enabled: true
      className: cilium
      hosts:
        - host: vpn.obmondo.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: vpn-obmondo-com-tls
          hosts:
            - vpn.obmondo.com

coturn:
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
