apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: fix_networking_for_capi_hcloud
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: cluster-autoscaler
  namespace: argocd
spec:
  destination:
    namespace: cluster-autoscaler
    server: https://kubernetes.default.svc
  sources:
    - repoURL: git@github.com:Obmondo/KubeAid.git
      path: argocd-helm-charts/cluster-autoscaler
      targetRevision: fix_networking_for_capi_hcloud
      helm:
        valueFiles:
          - $values/k8s/hcloud-vpn102/argocd-apps/values-cluster-autoscaler.yaml
    - repoURL: git@github.com:sbdtu5498/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  project: kubeaid
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
