apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: fix_networking_for_capi_hcloud
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: kubeaid
  sources:
    - repoURL: git@github.com:Obmondo/KubeAid.git
      path: argocd-helm-charts/sealed-secrets
      targetRevision: fix_networking_for_capi_hcloud
      helm:
        valueFiles:
          - $values/k8s/hcloud-vpn102/argocd-apps/values-sealed-secrets.yaml
    - repoURL: git@github.com:sbdtu5498/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
