---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAfiM0wcIACTKRP2Qh1ZbYuJUUsLYvXgJ5vVqrBKBoM02/StBY4JDElITOgaNwNLA0GDEhumqeH2ad/vtovuYW+mNOG1Ae00hEcSHbn12Gk3ZRRXvj29Y7tTs+U7FhwE2jgZlPkOJw/IvmuRlcQklE7mihgZfeRR+Ni83wEFLR2/rAHpIuh20zc8tWdKXdzG5urwz0n14zPL18DLOUvFshSP23ix+qmtXaAYT0Mm3bb/xXwp8+MpjH57UOXIJE8r++QIiphblvc3z6saPleU3NBSwcN4I748kmPSD4bU4P1b/i5Zak/utctZOJZTOKA5bVRZ42dFs9IE2dh21caevhkkG9Jxx9skvTqog9j0sJOjNddEx7qP6vCP93Re7xZi0e+69awH7H6anbzHRGWt79l4A2ZOYGIMX8wGAa1rGpG0S1QgZRXa+VALDCdLp2bWL0xVjQaJixKNJbC84cCoIEeWM9wy06ALuYKFJRfQml+N5MVXyv8pYpeUkorvyN+UUSMIla/qgtYQCTzA+kzP949Klw4dvM+bN9wufmI96EYE0vXuUPGkBsQzMgVIz+bxvHx3rrgRBRdU17gIfNcqtntuVrLJlnt1QgG4VRL1UuC9Q/Znb9FR61WSrZou9klri9QJ82RzVKv82zZM6awEYgCygXbVaqRqYeWCdQN0Y7cddeNI+ESr8NuiNAgV+0cnZLEd+4hnsT8CwXgyrJFpjlIc/Bad4Baojf9z/51SVMGbA72boCwgG+pYSufkQ/jHDJv0+lY0mFygqvvhvEmEy+2
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
