---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCYiO3UozRJiNnSuP9Gx/iySD42t0rsUkLOacgYGDVv4y0koEWrMXZYCfm4e0vdFsqqs0STGCEc69f7498I9WiHaPf5cu9u1xwbdbLm/adojl6zV++GI/AhbP9quKWglzaFD42as86rxOiFT/3mO4nMsbMuczxpsskSeattvN8IkwXRuT3dn5xkn6O0hsodkLSQLHCjKGd2xyX+XoWt/HaS9ckCESsXr7yg5gQJ0qX9rNiaTWoRtBF5J0kNNJkQIwDFNL8jP6nBapbt6uRicEFoz32Ntw6HUv4DyD7eWMryYIei/bZccIFPFLdwuX9xgpQnu4Zqr4qPJKrFYFC5iXO1scSMqOuKwd7qywu6V3TEUzxnfuyB7Y0UQTGES/QWRhzFFJbWy90KV7OFke8wHgwCLxhqU/aNFpFlJMxrD78928WxXj8J27/rBFhJfgz7xmqGL82aP0ZydlTKnXtCdpSI1wLGz/PeNfjlBxuNDcRb9Jf1RzyoYOIsygXC5L53ZBuxSYlXY8iDocUlBvDnRsyJAFS1JPtj+6MToK9yokMbA1Z0Xh9QFss6vKVW9osorm4ej0x41cw2GZg6O8eDkVHK8Tqga+/pacdI5Vujl+60G9hqW80psvLk6imfHso7RPTqS9tUsnJsFTUHFlSXoJyil0KCxHXEywgpr2EoD/YT6AVay0wYOOd0yavyvxrSPpWMDOG/jBNM746Z96Ma7OhuvJEIhw+qnLHIjP6Msk2e54OiYZYbcIpLoyTWDgHOuYMt0IaQfM0xpurQHDpK+yOW
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
