---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgB1DRg7/dOGN3VQ9AbFMyNke8VONkDq3isYA85as9K7P4vbyyaRM0TY91HekQoOmEaL73RbkIEGpJfydOUndYb2OzuH5lLRVrhB0q80kYuKqDxmEoZ+TEJr5GaYmvtASyQYS5HPYsYMplIsuW2gFnHGfvi5o1LIPtduGYiHKlusH4rJNwWowAO8ubs264V4tTGSFyJ2geOLOtNqpZdQLJv/CSg6JOnNAc9/tFmc3TSW/MHpDLt5ifs+oeNslf1ObxfqkLEnb5sHrhHlCMFjRCYCuaowiERq7A0xaXfTP6VYjOOtNHchs8vgt9QEpNszOZOstYz5B7vvuJHw2aDnbM6O9B8O7UUn2rHyF3ywnj1UVHEJtg1ZqWa23G/8Ebsk2fc3dum8lSnHzgBDzK+wZkJPGKFiJcsvzZChgrZp/w0HQbEbcF4OJKWGGT7LeItwf0IcFIk9Kd0GLOzN8BkOxYE3paSlpAZzZJpiKPUnv0zOIBXOINJG+lmE84c5N3R3BUgj//IFKxs6Oy/z8BTkYPhGMSbsmRbOtGkpU9cATXzHqxbuqsLqD9AMAPismz5ZGH+mG+pC85HUpicIrhdF2vzrgSbdLpqgLP7uD6Q8CSp67mKWNy2SRjgDv/2UPZ3jnHscltiiudTHRjxP1TacHEBp8LFeGQflwXv2RbV9ChZa9dggV1bjuF4pvrxJp/4FY5JxwU4voX1ZbuFc2blBCYKpZZhPx1ZxxgSNB3HAhFYGhZYIQ3PcXq89fX70pmm1BJq4XLICSgwLw1dDxFCeYtKO
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
