---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBSRsEt1ZS3djru3mnDr/YbXOAfQ3ocQeqEOttZA+I+2MWhwE9kO1YhH5h25Mr96BLeOkBiUkgx/2HUNsdkouRo0IkIIE+heMIOpB6DxE8OPXCKbpuFV2UknNsmZ2NdOnEAFmhojSozd5y3nlfK7+lYoHNKPMdvCDjrvsIANLmoRXs3sEl8l5nF4nAzRCLzdEHWMoMK30/zn85H1a3HXHjAkd5isB3Z1WP4s9yUhdhlI5O5RSVPhVVpnUoNakcvFuSBZYc2dVTVt5/0noYTTq9IwrPMzRIY4Ub2+u/XmAy9thdrtNUWPXz8tdndtoTJ8gw4hy02huJV844TTATfreDW4P4RVjLD3DponhVjjC5ufb+w3P9kBNph6JA2LxUJjMkk3Xa4zzclTCiWM8sxXQWeWi/+E3ay5l3NxyXXfgdata0TNLVaECnsPylsJqcRIHSJClN8ZYaVsv5O9KfM9gBEs9UIYoG0+bs1juC5J8Xi/a3Nle5E8vETAM4vHIBNkEJIJsfcRumXlBvAHJ9V3oy5tsSl/HalcMMrc+AhtZw1w62W6Ttdeb/OhNIi02+Iv+2b41DREU/fNadfs7jP8mw15lEkhU0RmiPGcWU8JL1/1W5M6phxqUDdP9Hh263pg0Hj25vAiNuU1WpN6hSuZMTgQsYFs4WNOu1VCK1y77eSba1q/AEHRQ9jjmKjbJFoI+s8IDg5lEyF+y19o2u5vb9hLLxUFhti8j9Qf89Jtv9izKp01T27rpgSAaRnfrS7BnKd+cwE0ZtXHzRobzdbnMxs
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
