---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBd4C201aQOcxJ24RkwiybbI6O0nA5C40c6NEDe3nqxrzJkdhpJ3WHFFKOJnH93xQee2L292rX3LUqCkDNqsVYGY9iofM9IeAo5ij/X9CRow1lo/IhXavBQH1Z6eSCqSIt7e3dtYj+1WFysRA0eT0fBLnVtxzaKEguXqAF/Nfrune5vICnkcHntJglV+DI9gU0z2J2N6nNgX6gsNqSwmW+ok+j2JQS/UfCBiARP0glP7m4cGU2VrpNjI3pmTw+fJulsgnJ9C8w85gAeMpkAN3HvhSxqtNVkVdcAflNRFr5a5LXvuzac1AuGjsXkV5ikViu93L+X6q2v4rDHmyDZLuk9NztoFW43Xp9f384N2Nsp3CLtz8NbO8S+TobMiX4oqzoHz2AF4C5+EDk1Ujx9UuSYOXh1cyAbhaIadFquCs1ucB3sfLM+Tl1IoTD7MduPaa0w/asnCGYta6RCXkt61CE4+5Dn5PLYaIRV+P4QZsD4V8Pi+G6mb2vQjVU6mb3TrzxZAozOcsw4x2K8ozFBV+IWqImDFd36yAJBqKUQSXGCwRHw50ZgMKBl9A+GAuCHHssoS5Q6hUGltCk3MoTokkqEQ+rOJCZiBgq4KYB+v9VXZZIWkA5T77Jg6GdMZoluiALmsMcZF8zJOmdbgysbkgP0Z0PO4j56ZTPqp+tJUGFN2IOh8ZXQXbJvbtiFw78LVkJWJypQWs85dXTpGklBJkR/mCJmynzz8ZgJvhWK+J5s0nShkTdZis89Dl5jDlnO2FQH66y6xYwmWkXPVyra1Jo/
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
