---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgDJUgpRpn8b/G3Wvb/22pXb4i5BIiS+6d3mgQv7y8TcjwjWQ5rGvTcWscztnkrB4bOPb9fXZYTF2VJTNLzmCmAcS9F+gB/X9NrMObUL55SV0fWoXvDqfnwwIAHccHSbHQIyvvXkpEhGtJoaxnHjsQHjcnOHp6KgsE+q7AhEpyCRadzWe+Rp/mv1wX0X5EfYQpMgQo4IR/bhL57yeWkUroVGAUQVOzOWDYv3lJGsvLaJshubAycnGtDqwt0C9uShYzvlndoISsIiExiTVFGOioufb99xUpkCvCRsjPWqZbNGcbf+5ressbH5u4frowWb5u0RROsTA59VAsz9G2TQX2aUJIGEdf9bM+QXAiR7sqD91hedXTNAjSiaFqykg1iEFIl4enMq8nZsGB23ZhiH/MCzhCbqowie039/mGpRx2set51QBx4ztVCuSbzU3M4x/98dbWQeMptcnWQsOkkU1jrtBId9Bi/6jSjMAWIu4Xc7gvwYoX2Oj+0EL6kHAdubbTzRDvHNLthp4XMRn2efRWV7TfyNGl/uWL+cUUPj8Hlec4aw30LM0cMD9EMHjkLx/6Lu38giepBVXP6nI5gj5O878g05kMbINp+ZIL9iFAj6B3zX05Wy/1jNF69i4z0eRKgnGoKtR6CRHiNke9GaXH9TN03m8PUprZl+M11MHfUfvfoZ7f8TwB/Pv1w3oSXjRNTqWNwieEmj32tWN3PFXX2Md6TWqtQgQRE1KtCETGlkm0n/VMBhAiJQ3XohKDYBgHb3xnS4YhAaiuNnLf+Z9mTK
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
