---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgDcnwcBKvNtGm9QPbdZf9uU6YBMLUB1KijzOgSq6Xy0JVg0NAUXLY9nFiKM29kF4/hb99PUUmgNECd0U9drPnWda7EpBHh7aS5vpF5ilKwvlJuKcJ0xCn8xnaLxsHOJ814gZIhkKWbu6ccOZF67YMcu/EhNmNF/nvwVwWpkhkCiu0XJIDaYoK4bEdf3RStvRI8eC4Cap1tH3kGfT8wZECkGoCFjRzTcwkDFkyKtJgr3yFFvqfx43ot6EuuZmXoUX9lP0U0NZ/xaBRFIYVWU1JJW75auRSDcTlgpm0Uz7EippmkbyzCYohnokaNblWEJmQ9lfD+w2m7CJIXKcdc4dX39IxjK0cgxZMK6VElwLDxAUkKK0NX5BUKPD07X/CESN++19OfRh74XNIAhKreIkpQLLDo4GDEDlgPKP3jyK0JjePLDBkZ1rRcn5+fJNDrS2+Ta//VgF56flauijYeUw0HdVWQ4QHw6CPKpigPvGScgfeJcIp90b9XwWyLx++LoQYla0woELOiWoI8nJ+BzuFKPXBKKjnDzld8TEovKTkyJMRLulZo2+TLCM5oY1qwY9Jz7zPFAYWA+FRfDJvW6HKIWsJKXF1hRJAWN2L/96TW4MC1wseqUHf5rtOcG8ZCASW1tIlnCbPzt/giylGxsyOeunkFLOWsGjb7uQKKZU3gRu99BN/OhYOgUXbJB76MRPr0nnUqDm4a6Qa0ie6zTE0+kwNkB12ZUHZTmjlukxIE+zVcGXlaj3tBTbS08YTc7KNmyi7ImUp+ayJntfzVdgp9T
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
