---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBhh5W8b28Uw2dy8iOecmdn0W82UAvd37u64z6kG6+rhJ3p0rKzqsMQQkh7Ys1yY/Sq1MZ2iYizkJ8wC3RRlZ/PIl08Jf9kTqD8oY50GxSxCiBNhWgO7RiGWIUzYDL2YOfj2hzFi2PWEBDTwMH+KiCcpB60K6j/u1LQScVMH9IyqAjQpz6ZI9/cG+w9sWwJSl8VesVnyGKkaDGIYvxHpi8+tXtdPzfjYhCWR4SRvwZQsGUBwe/xYMU7rsqSKtgi+3OxT5036Txn7Cha7qBMZgmp/T7ILGQt5s6WXnSWgA3xVi0PUk0XhykOJehvtoIVEfkwfeyvNb4q1M8YVNA9g1cYwuBohprwgDbu3NgkR6CirnJDcVvU4UYxM8gXpfx2ST+5wVyx26pP7ekHGYeqcAhj+2V+Krd/oz+35l0OO88OrAMqbQFxc1HCIsnu49UTbzqXcD3LKAsd+YH4JVnWtLJsgUA6kTtpkeLFG2kXrSbSS6eWylVGp1izitIDilrOtcg/ORH91t9hOGKvqQn7spq++ZYtb3Ncn/dWYWdwRR87lsXTiFGSh7NtM9Rg+4odfGFx7GpaOeznzolpu5l9P19qo/FEubR5lbP88GE0NZOkSmnzt37upoo0DcDty/jhWPZKhymntHBp8DDO5EsOjfvo0NL8ZfbXs3ZoCLjPXD02GFLnWWQwuGk5zErmspRlz9UHc05Z8lj0e86YM0vtBW0qdyN6qbp7m3mtnMRrhk+YnGUZUcVJ5A9fogfb2TH2oABl/TTCO2gg1iDSoR7M+vpt
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
