---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCHbNfuP21eJzIXrs2qOvqTBdN2gA2SV8z9lPun3Z/SfME+JLV4iY39A3Zgih1AouMa2pg6B7SZNJZXiQSmJ0Qj8oEu1miSFTs5esxx6XAIf7IsBrBhh/YqjwFhTdjQVfBrX2kJSBuKlRJcHPdoj9ARnukndvOmhiJ1pvT87IaJBcBQCR1M7ZKDdh6szvZWTcL+3fZK1erqHaM2ZGrB+CxTAicvakBGg5ThZ4NvdOtFIHbmfxDBq1mEa7j0qd4aIp4qZ1r87IIk37mm2bfZ8eCoOsSuuIngx6tJFE2qgIftaULji21YAu92KZpPlFNtesBcL2xGMDD/TkpRXnTFRFYYKYK9cbsJcnx5Lk1fM3cF+8nykabiGfmUHhlS2URSEVSdSV8WAs6hF7jr+gCNoUMOj4H0AaACgOc08M49WqRvJvg+FiBY/gKII9Y671nst747cEddftSElDIFBCyEap7koEplzjh8r1YUzIHxgeNyeub/oz7NLsHd/ICppAWW6deKcLsXFu+9+4W18h+PqiBHTkTOBm+x9QjaEegXdOH5zxdvC7ebSzmKnji/XSb+U53sAnV5BMBuYQe+RLqgggzySSf2TTHAZk5VjmDhxoO4HXArHo+YbO+NtoZoveOjAP4xenususgcA6pcyIEXmAOfvhtU0rpBxENNIYX5BuYcKT165rihihmm+4T3kbF7Z05OdszKb3LW8lLIMSCEi6agl4enjzvvTy79rxqItV5rYeozpFS1KTz30Q8vJm/MCi/stZQBBLddGox5wc/C3dvI
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
