---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgA9Fu1r2gTEPtm6wtuI3NPZVs3XvLpzdW13kDH27t3FEzDWo+aHoXAaeKIn7Cf8WuQ0JT8XTg6RJLfn63GSwcTMYM1o6nIDzCw8T22mVtwQ/WCjEFRoB+fx/zgELATbCrpWJS+0FSK9tmOEPAP6oybwMO4nvzha29supp1I2KkupX3m9twRkPuyHVTXByf3j5nZ3zeXZVryIwZHxvKuw4nD1+LiuKFW9nZl0qeGF64VqZr5TupMHv6QuPDSmdf8aJZ3KyXJZE3U6PaSJ4Jk00TVtzo5hzs7dj1Pbo9n2ZqM32uA2S1E1Ntpst7hvcZzczavr/2Bo4RVyh0jfMAZx4QsNcAX7ENV6WehXDBEjlYNA7k+l6qcr9hlN0oGOxkamqbWNjM2/anbMhzJe3RUDtRLpOeOJ/K8QRkeihy2Ty1x1GTjeJKpbAM8EaDQU+1AURq6297xJOSROPcR6Yh+8Bt4AFrlDSG5pBdifLTU8NAmeF3pI2d8Ujsvo/FNeyYXZDRu4Ki8/Qrycq7DTziUUuN6zs5SSrDt4CuOKB7avXbwR1Y1gCgqqVGuuqqpSwzI8nCD9PUXgvtp+pF/q25SS76RglxY0YpvEY/yNazbeqD1IbbW9ExO/SoSRbK4Xttk+cvIwh68trEbz7UWcQmujbaGnqvgCvqxwMe3A52yFxLDD4/1X9njEqa1tnSRff82zdEbwYVRCxTVosyd3GkGQKI0svlNdYQM1X0BDvzzLGJAK7b6+6uLLrzNl59wgXcG/+HnthzUEjaCRNM5AkZyjIos
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
