---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBRWAgJ9g/BhtJ0LCuLy7UPjLNdADsw+aKP+YfV3F4mfW/cXhlEmo/27NNR3vejGwmSTBJtrP3HAkrZBu6ZdSCqGfvZGBfQzqTXyGmFAZz1ZjUb/7RFK7M4SKj1mqQoJU0gdm8Zzk83rGI63sicMBaqOGvHLx+zYaepEGI/gLgbY9rnAf2F1CZ/OcprvAfwbOaiL33c8Tkb0sX16XVD0mQryPp8nWIySiIlWGkkm4RfeufbapvrbQBT2dbBKSFbSwUoY7fkWrpOXNWOZ+fULVJ6WDy+z/qAXZCNokuvvrH6IAVGax82rN5tUAs7ivsFKK5aGK3Qifz/Zoiy6fPAMu+0Q2jRjn420w58/GpbVbgnnica/KjNnTvqQx+lIoEaOoWhZg67RV6khfvyM0hkrof1CW6M55l0oI39hk9PIpr44JZG7vfA8rO4tYLCk0rl6Amz4vEfQtqVDqbX6kdw7V6RcoQhJoxgfpzyf64ICICczn4vbrclfhOT2gFT5Nlvm1dUyCBR1OytAh4WUoEnJ5cUzinm3n6E+1oUhMWRqpEo/hScVt7Vctz69Quxz0KRzSVzwwOPUmar8gmnu5p5ZUd37v3LzjauJyTJPrQmfyEkUsHOIg2/X3xaTiK7WbdeHyd1I0dLUVLtrMy6R0d13BB5RF9zQdUuk13U+ocVJOtkxThANYtuocHPqcElWYKK+Ve9zNBtx2VUK8aau8rpAo2Bc0lEHGZ47V1OvR89gk+7xih6HQnnJVsvd8uC0tW8bZqL9fZufmg/d+38oiccIFXl
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
