---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAwUA/IuejAlvjovtWEqqxtlbuszLm8UHzvJ4AAzvRMTbSUxcGAXFPG+VIRhVBbkMg/WidBpRfJSiA7/mzTRuGO4VK8lL7gcag//bfZJWVdKbqalPAOsseNST1fr1wSkV4+I4YhV9jpXL4jYTQi87xwJPSDPCX0HodkxLmBmTfAVwOd8tj1h56sLfNfrB0+LKib2azmYwRSzaiG3TQEA0VBNXjImiP8A6BSZWyaVRuUDEI52qC7qcIC/CChzhB3ncTnMqNT1y4HiA0MsaL1HXRC05/zN9WLd87Wti+jDlhcSpvewFHVPexZUy+jr0LAX3bcfq52Od9NShocfWUmNOMkvuuLKaJX5fcH0FGIDmjkrz4mAozhzOSlR9k8qIvx1PCXWZdV5XIkzWnKJ2kloHJ8iOfgLFsRNTXsSI7GO/tQFjKbbIiaV6HgJ58kdYun1sj+Z1Q5bmcQAVm1ik9EN1vCIBiF/3glDg6Wv708uiX4ppInLcRB7RnQul+aXAiejDxdmaf+xnJNESfBOjtwFrarcdTrlXHOu9nE+G220b1g5oV4rCDNRKCUnt7biLyw39KhLxU3CM/W1uWZ+HLJL2xs/9LZv0naxfJG+I7bOlP8bMO+5kRAGJ7F4ZKEWdZuEDAFcSuuBl67yL7A0ZvnGwk52YvPQOw4nLHFcs5ws5GXmUhiDVtOcFzxMXczKn+4KcuxJ8WUlMvTpWxTtyM2Py5JRtgWsOf/k0vuBDIBZlRj7nYYsIZuD2wqwX64KJRP52nTwTTEO26q8/EI5Nvvvck1
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
